#Generated by VPC

NAME=vscript
TARGET_PLATFORM=linux64
TARGET_PLATFORM_EXT=_client
VPC_HOST=linux

SRCROOT=..
LINUX_MAKEFILE=1
USE_VALVE_BINDIR=0
# If no configuration is specified, "release" will be used.
CFG ?= release




















################################################################################
#
# CFG=debug
#
################################################################################

ifeq "$(CFG)" "debug"

GCC_ExtraCompilerFlags=
GCC_ExtraCxxCompilerFlags=
GCC_ExtraLinkerFlags=
DisableLinkerDeadCodeElimination=
SymbolVisibility=hidden
TreatWarningsAsErrors=false
OptimizerLevel=-gdwarf-4 -g2 $(OptimizerLevel_CompilerSpecific)
PrecompiledHeaderInclude=
SystemLibraries=
DLL_EXT=_client.so
SYM_EXT=.dbg
DEVTOOLS := ../devtools
MAKEFILE_BASE := $(DEVTOOLS)/makefile_base_posix.mak
COMPILE_DEPENDANT_MAKEFILES := vscript_linux64.mak $(MAKEFILE_BASE)
FORCEINCLUDES= 
DEFINES += -DVPC -DCSTRIKE_REL_BUILD=1 -DRAD_TELEMETRY_DISABLED -DDEBUG -D_DEBUG -DGNUC -DPOSIX -DCOMPILER_GCC -DMEMOVERRIDE_MODULE=vscript -D_DLL_EXT=_client.so -D_LINUX -DLINUX -DPOSIX -D_POSIX -DDLLNAME=vscript -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DUSE_SDL -DCSTRIKE15 -DVSCRIPT_DLL_EXPORT -DLUA_MOD_CASE_INSENSITIVE -D_DLL_EXT=_client.so -D_DLL_PREFIX=lib -D_EXTERNAL_DLL_EXT=.so -D_LINUX=1 -D_LINUXSTEAMRT64=1 -D_POSIX=1 -DLINUX=1 -DLINUX64=1 -DLINUXSTEAMRT64=1 -DPOSIX=1 -DPROJECTDIR=/home/lwss/Documents/cstrike15_src/vscript -DVPCGAME=csgo -DVPCGAMECAPS=CSGO 
INCLUDEDIRS += ../common ../public ../public/tier0 ../public/tier1 ../thirdparty/SDL2 ./languages/squirrel/include ./languages/squirrel/sqplus ./languages/lua/lua-5.1.4/src 
CONFTYPE=dll
IMPORTLIBRARY=
OUTPUTFILE=$(OBJ_DIR)/vscript_client.so
GAMEOUTPUTFILE=../../game/bin/linux64/vscript_client.so

CPPFILES= \
    ../public/tier0/memoverride.cpp \
    vscript.cpp \
    languages/squirrel/vsquirrel/vsquirrel.cpp \
    languages/squirrel/squirrel/sqapi.cpp \
    languages/squirrel/squirrel/sqbaselib.cpp \
    languages/squirrel/squirrel/sqclass.cpp \
    languages/squirrel/squirrel/sqcompiler.cpp \
    languages/squirrel/squirrel/sqdebug.cpp \
    languages/squirrel/squirrel/sqfuncstate.cpp \
    languages/squirrel/squirrel/sqlexer.cpp \
    languages/squirrel/squirrel/sqmem.cpp \
    languages/squirrel/squirrel/sqobject.cpp \
    languages/squirrel/squirrel/sqstate.cpp \
    languages/squirrel/squirrel/sqtable.cpp \
    languages/squirrel/squirrel/sqvm.cpp \
    languages/squirrel/sqdbg/sqrdbg.cpp \
    languages/squirrel/sqdbg/sqdbgserver.cpp \
    languages/squirrel/sqstdlib/sqstdaux.cpp \
    languages/squirrel/sqstdlib/sqstdblob.cpp \
    languages/squirrel/sqstdlib/sqstdmath.cpp \
    languages/squirrel/sqstdlib/sqstdrex.cpp \
    languages/squirrel/sqstdlib/sqstdstream.cpp \
    languages/squirrel/sqstdlib/sqstdstring.cpp \
    languages/squirrel/sqplus/SqPlus.cpp \
    languages/squirrel/sqplus/SquirrelBindingsUtils.cpp \
    languages/squirrel/sqplus/SquirrelObject.cpp \
    languages/squirrel/sqplus/SquirrelVM.cpp

unexport CPPFILES

LIBFILES = \
    ../lib/public/linux64/tier1_client.a \
    ../lib/public/linux64/interfaces_client.a \
    ../lib/public/linux64/mathlib_client.a \
    -L../lib/public/linux64 -ltier0_client \
    -L../lib/public/linux64 -lvstdlib_client

unexport LIBFILES

LIBFILENAMES = \
    ../lib/public/linux64/libtier0_client.so \
    ../lib/public/linux64/tier1_client.a \
    ../lib/public/linux64/interfaces_client.a \
    ../lib/public/linux64/libvstdlib_client.so \
    ../lib/public/linux64/mathlib_client.a

unexport LIBFILENAMES

ALL_CUSTOM_BUILD_TOOLS = \
    $(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/sentinels/languages_dir_squirrel_dir_vsquirrel_dir_init_dot_nut

unexport ALL_CUSTOM_BUILD_TOOLS

ALL_CUSTOM_BUILD_TOOL_DEPENDENCIES = \
    languages/squirrel/vsquirrel/init.nut \
    ../vpc_scripts/vpc_trivial_dependency.txt

unexport ALL_CUSTOM_BUILD_TOOL_DEPENDENCIES

ALL_CUSTOM_BUILD_TOOL_SCRIPTS = \
    _vpc_/generated_scripts_vscript/linux64/Debug/custom_build_tools/languages_dir_squirrel_dir_vsquirrel_dir_init_dot_nut.sh

unexport ALL_CUSTOM_BUILD_TOOL_SCRIPTS

ALL_CUSTOM_BUILD_TOOL_OUTPUTS = \
    languages/squirrel/vsquirrel/init_nut.h

unexport ALL_CUSTOM_BUILD_TOOL_OUTPUTS

ALL_DEPGEN_FILES = \
    $(OBJ_DIR)/memoverride.P \
    $(OBJ_DIR)/vscript.P \
    $(OBJ_DIR)/vsquirrel.P \
    $(OBJ_DIR)/sqapi.P \
    $(OBJ_DIR)/sqbaselib.P \
    $(OBJ_DIR)/sqclass.P \
    $(OBJ_DIR)/sqcompiler.P \
    $(OBJ_DIR)/sqdebug.P \
    $(OBJ_DIR)/sqfuncstate.P \
    $(OBJ_DIR)/sqlexer.P \
    $(OBJ_DIR)/sqmem.P \
    $(OBJ_DIR)/sqobject.P \
    $(OBJ_DIR)/sqstate.P \
    $(OBJ_DIR)/sqtable.P \
    $(OBJ_DIR)/sqvm.P \
    $(OBJ_DIR)/sqrdbg.P \
    $(OBJ_DIR)/sqdbgserver.P \
    $(OBJ_DIR)/sqstdaux.P \
    $(OBJ_DIR)/sqstdblob.P \
    $(OBJ_DIR)/sqstdmath.P \
    $(OBJ_DIR)/sqstdrex.P \
    $(OBJ_DIR)/sqstdstream.P \
    $(OBJ_DIR)/sqstdstring.P \
    $(OBJ_DIR)/SqPlus.P \
    $(OBJ_DIR)/SquirrelBindingsUtils.P \
    $(OBJ_DIR)/SquirrelObject.P \
    $(OBJ_DIR)/SquirrelVM.P

unexport ALL_DEPGEN_FILES


#
# Include the base makefile now.
#
include $(MAKEFILE_BASE)


#
# Create sentinel directories
#
$(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/_vpc_create_dirs: vscript_linux64.mak | $(OBJ_DIR)/_create_dir
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) create custom build tools dir start
	$(QUIET_PREFIX) $(MKDIR) -p $(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/locks $(QUIET_ECHO_POSTFIX)
	$(QUIET_PREFIX) $(MKDIR) -p $(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/ranthisbuild $(QUIET_ECHO_POSTFIX)
	$(QUIET_PREFIX) $(MKDIR) -p $(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/sentinels $(QUIET_ECHO_POSTFIX)
	$(QUIET_PREFIX) $(TOUCH) $(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/_vpc_create_dirs


#
# Custom Build Tool "init.nut produces init_nut.h" for file "languages/squirrel/vsquirrel/init.nut"
#
DEPENDENCIES_FOR_BUILD_TOOL_languages_dir_squirrel_dir_vsquirrel_dir_init_dot_nut = \
    languages/squirrel/vsquirrel/init.nut \
    ../vpc_scripts/vpc_trivial_dependency.txt

unexport DEPENDENCIES_FOR_BUILD_TOOL_languages_dir_squirrel_dir_vsquirrel_dir_init_dot_nut

ORDER_ONLY_DEPENDENCIES_FOR_BUILD_TOOL_languages_dir_squirrel_dir_vsquirrel_dir_init_dot_nut =

unexport ORDER_ONLY_DEPENDENCIES_FOR_BUILD_TOOL_languages_dir_squirrel_dir_vsquirrel_dir_init_dot_nut

CUSTOM_BUILD_TOOL_ACTION_languages_dir_squirrel_dir_vsquirrel_dir_init_dot_nut = \
    { \
        $(ECHO) "init.nut produces init_nut.h" && \
        { $(SHELL) _vpc_/generated_scripts_vscript/linux64/Debug/custom_build_tools/languages_dir_squirrel_dir_vsquirrel_dir_init_dot_nut.sh $(PROCESS_COMPILER_OUTPUT); } && \
            $(TOUCH) "$(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/sentinels/languages_dir_squirrel_dir_vsquirrel_dir_init_dot_nut" || \
            { $(ECHO) "Error executing custom build tool \"_vpc_/generated_scripts_vscript/linux64/Debug/custom_build_tools/languages_dir_squirrel_dir_vsquirrel_dir_init_dot_nut.sh\""; false }; }; \
    }

unexport CUSTOM_BUILD_TOOL_ACTION_languages_dir_squirrel_dir_vsquirrel_dir_init_dot_nut

OUTPUTS_FOR_BUILD_TOOL_languages_dir_squirrel_dir_vsquirrel_dir_init_dot_nut = \
    languages/squirrel/vsquirrel/init_nut.h

unexport OUTPUTS_FOR_BUILD_TOOL_languages_dir_squirrel_dir_vsquirrel_dir_init_dot_nut

POTENTIAL_OUTPUTS_FOR_BUILD_TOOL_languages_dir_squirrel_dir_vsquirrel_dir_init_dot_nut =

unexport POTENTIAL_OUTPUTS_FOR_BUILD_TOOL_languages_dir_squirrel_dir_vsquirrel_dir_init_dot_nut

_prebuild_always::
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) _prebuild_always for custom build tool languages_dir_squirrel_dir_vsquirrel_dir_init_dot_nut start
	$(QUIET_PREFIX) $(RM) -fr $(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/ranthisbuild/languages_dir_squirrel_dir_vsquirrel_dir_init_dot_nut
	$(QUIET_PREFIX) $(RM) -fr $(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/locks/languages_dir_squirrel_dir_vsquirrel_dir_init_dot_nut

$(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/sentinels/languages_dir_squirrel_dir_vsquirrel_dir_init_dot_nut $(OUTPUTS_FOR_BUILD_TOOL_languages_dir_squirrel_dir_vsquirrel_dir_init_dot_nut): _vpc_/generated_scripts_vscript/linux64/Debug/custom_build_tools/languages_dir_squirrel_dir_vsquirrel_dir_init_dot_nut.sh $(DEPENDENCIES_FOR_BUILD_TOOL_languages_dir_squirrel_dir_vsquirrel_dir_init_dot_nut) | _prebuild_steps $(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/_vpc_create_dirs $(ORDER_ONLY_DEPENDENCIES_FOR_BUILD_TOOL_languages_dir_squirrel_dir_vsquirrel_dir_init_dot_nut)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) custom build tool for languages_dir_squirrel_dir_vsquirrel_dir_init_dot_nut start
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(QUIET_PREFIX) $(call RUN_RECIPE_ACTION_ONCE,"$(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/ranthisbuild/languages_dir_squirrel_dir_vsquirrel_dir_init_dot_nut","$(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/locks/languages_dir_squirrel_dir_vsquirrel_dir_init_dot_nut",$(call CUSTOM_BUILD_TOOL_ACTION_languages_dir_squirrel_dir_vsquirrel_dir_init_dot_nut))


#
# include all the depgen .P files which will include dependency information.
#
include $(wildcard $(OBJ_DIR)/memoverride.P)
include $(wildcard $(OBJ_DIR)/vscript.P)
include $(wildcard $(OBJ_DIR)/vsquirrel.P)
include $(wildcard $(OBJ_DIR)/sqapi.P)
include $(wildcard $(OBJ_DIR)/sqbaselib.P)
include $(wildcard $(OBJ_DIR)/sqclass.P)
include $(wildcard $(OBJ_DIR)/sqcompiler.P)
include $(wildcard $(OBJ_DIR)/sqdebug.P)
include $(wildcard $(OBJ_DIR)/sqfuncstate.P)
include $(wildcard $(OBJ_DIR)/sqlexer.P)
include $(wildcard $(OBJ_DIR)/sqmem.P)
include $(wildcard $(OBJ_DIR)/sqobject.P)
include $(wildcard $(OBJ_DIR)/sqstate.P)
include $(wildcard $(OBJ_DIR)/sqtable.P)
include $(wildcard $(OBJ_DIR)/sqvm.P)
include $(wildcard $(OBJ_DIR)/sqrdbg.P)
include $(wildcard $(OBJ_DIR)/sqdbgserver.P)
include $(wildcard $(OBJ_DIR)/sqstdaux.P)
include $(wildcard $(OBJ_DIR)/sqstdblob.P)
include $(wildcard $(OBJ_DIR)/sqstdmath.P)
include $(wildcard $(OBJ_DIR)/sqstdrex.P)
include $(wildcard $(OBJ_DIR)/sqstdstream.P)
include $(wildcard $(OBJ_DIR)/sqstdstring.P)
include $(wildcard $(OBJ_DIR)/SqPlus.P)
include $(wildcard $(OBJ_DIR)/SquirrelBindingsUtils.P)
include $(wildcard $(OBJ_DIR)/SquirrelObject.P)
include $(wildcard $(OBJ_DIR)/SquirrelVM.P)


#
# Compare/cache a string of compile settings to see if we need to recompile .o's
#
$(eval $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS,COMPILE_O_GLOBAL_SETTINGS,$$(call COMPILE_O_SETTINGS,$$(CFG_CPPFLAGS))))


#
# Compile rules
#
$(OBJ_DIR)/memoverride.o: ../public/tier0/memoverride.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/memoverride.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/memoverride.o

$(OBJ_DIR)/vscript.o: vscript.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/vscript.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/vscript.o

$(OBJ_DIR)/vsquirrel.o: languages/squirrel/vsquirrel/vsquirrel.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/vsquirrel.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, -DVPC -DCSTRIKE_REL_BUILD=1 -DRAD_TELEMETRY_DISABLED -DDEBUG -D_DEBUG -DGNUC -DPOSIX -DCOMPILER_GCC -DMEMOVERRIDE_MODULE=vscript -D_DLL_EXT=_client.so -D_LINUX -DLINUX -DPOSIX -D_POSIX -DDLLNAME=vscript -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DUSE_SDL -DCSTRIKE15 -DVSCRIPT_DLL_EXPORT -DLUA_MOD_CASE_INSENSITIVE -D_DLL_EXT=_client.so -D_DLL_PREFIX=lib -D_EXTERNAL_DLL_EXT=.so -D_LINUX=1 -D_LINUXSTEAMRT64=1 -D_POSIX=1 -DLINUX=1 -DLINUX64=1 -DLINUXSTEAMRT64=1 -DPOSIX=1 -DPROJECTDIR=/home/lwss/Documents/cstrike15_src/vscript -DVPCGAME=csgo -DVPCGAMECAPS=CSGO  $(addprefix -I, $(abspath ../common ../public ../public/tier0 ../public/tier1 ../thirdparty/SDL2 ./languages/squirrel/include ./languages/squirrel/sqplus ./languages/lua/lua-5.1.4/src ./languages/squirrel/include ./languages/squirrel/sqplus ))) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/vsquirrel.o

$(OBJ_DIR)/sqapi.o: languages/squirrel/squirrel/sqapi.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/sqapi.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, -DVPC -DCSTRIKE_REL_BUILD=1 -DRAD_TELEMETRY_DISABLED -DDEBUG -D_DEBUG -DGNUC -DPOSIX -DCOMPILER_GCC -DMEMOVERRIDE_MODULE=vscript -D_DLL_EXT=_client.so -D_LINUX -DLINUX -DPOSIX -D_POSIX -DDLLNAME=vscript -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DUSE_SDL -DCSTRIKE15 -DVSCRIPT_DLL_EXPORT -DLUA_MOD_CASE_INSENSITIVE -DPROTECTED_THINGS_DISABLE -DVSCRIPT_DLL_EXPORT -D_DLL_EXT=_client.so -D_DLL_PREFIX=lib -D_EXTERNAL_DLL_EXT=.so -D_LINUX=1 -D_LINUXSTEAMRT64=1 -D_POSIX=1 -DLINUX=1 -DLINUX64=1 -DLINUXSTEAMRT64=1 -DPOSIX=1 -DPROJECTDIR=/home/lwss/Documents/cstrike15_src/vscript -DVPCGAME=csgo -DVPCGAMECAPS=CSGO  $(addprefix -I, $(abspath ../common ../public ../public/tier0 ../public/tier1 ../thirdparty/SDL2 ./languages/squirrel/include ./languages/squirrel/sqplus ./languages/lua/lua-5.1.4/src ./languages/squirrel/include ./languages/squirrel/sqplus ))) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/sqapi.o

$(OBJ_DIR)/sqbaselib.o: languages/squirrel/squirrel/sqbaselib.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/sqbaselib.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, -DVPC -DCSTRIKE_REL_BUILD=1 -DRAD_TELEMETRY_DISABLED -DDEBUG -D_DEBUG -DGNUC -DPOSIX -DCOMPILER_GCC -DMEMOVERRIDE_MODULE=vscript -D_DLL_EXT=_client.so -D_LINUX -DLINUX -DPOSIX -D_POSIX -DDLLNAME=vscript -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DUSE_SDL -DCSTRIKE15 -DVSCRIPT_DLL_EXPORT -DLUA_MOD_CASE_INSENSITIVE -DPROTECTED_THINGS_DISABLE -DVSCRIPT_DLL_EXPORT -D_DLL_EXT=_client.so -D_DLL_PREFIX=lib -D_EXTERNAL_DLL_EXT=.so -D_LINUX=1 -D_LINUXSTEAMRT64=1 -D_POSIX=1 -DLINUX=1 -DLINUX64=1 -DLINUXSTEAMRT64=1 -DPOSIX=1 -DPROJECTDIR=/home/lwss/Documents/cstrike15_src/vscript -DVPCGAME=csgo -DVPCGAMECAPS=CSGO  $(addprefix -I, $(abspath ../common ../public ../public/tier0 ../public/tier1 ../thirdparty/SDL2 ./languages/squirrel/include ./languages/squirrel/sqplus ./languages/lua/lua-5.1.4/src ./languages/squirrel/include ./languages/squirrel/sqplus ))) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/sqbaselib.o

$(OBJ_DIR)/sqclass.o: languages/squirrel/squirrel/sqclass.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/sqclass.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, -DVPC -DCSTRIKE_REL_BUILD=1 -DRAD_TELEMETRY_DISABLED -DDEBUG -D_DEBUG -DGNUC -DPOSIX -DCOMPILER_GCC -DMEMOVERRIDE_MODULE=vscript -D_DLL_EXT=_client.so -D_LINUX -DLINUX -DPOSIX -D_POSIX -DDLLNAME=vscript -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DUSE_SDL -DCSTRIKE15 -DVSCRIPT_DLL_EXPORT -DLUA_MOD_CASE_INSENSITIVE -DPROTECTED_THINGS_DISABLE -DVSCRIPT_DLL_EXPORT -D_DLL_EXT=_client.so -D_DLL_PREFIX=lib -D_EXTERNAL_DLL_EXT=.so -D_LINUX=1 -D_LINUXSTEAMRT64=1 -D_POSIX=1 -DLINUX=1 -DLINUX64=1 -DLINUXSTEAMRT64=1 -DPOSIX=1 -DPROJECTDIR=/home/lwss/Documents/cstrike15_src/vscript -DVPCGAME=csgo -DVPCGAMECAPS=CSGO  $(addprefix -I, $(abspath ../common ../public ../public/tier0 ../public/tier1 ../thirdparty/SDL2 ./languages/squirrel/include ./languages/squirrel/sqplus ./languages/lua/lua-5.1.4/src ./languages/squirrel/include ./languages/squirrel/sqplus ))) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/sqclass.o

$(OBJ_DIR)/sqcompiler.o: languages/squirrel/squirrel/sqcompiler.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/sqcompiler.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, -DVPC -DCSTRIKE_REL_BUILD=1 -DRAD_TELEMETRY_DISABLED -DDEBUG -D_DEBUG -DGNUC -DPOSIX -DCOMPILER_GCC -DMEMOVERRIDE_MODULE=vscript -D_DLL_EXT=_client.so -D_LINUX -DLINUX -DPOSIX -D_POSIX -DDLLNAME=vscript -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DUSE_SDL -DCSTRIKE15 -DVSCRIPT_DLL_EXPORT -DLUA_MOD_CASE_INSENSITIVE -DPROTECTED_THINGS_DISABLE -DVSCRIPT_DLL_EXPORT -D_DLL_EXT=_client.so -D_DLL_PREFIX=lib -D_EXTERNAL_DLL_EXT=.so -D_LINUX=1 -D_LINUXSTEAMRT64=1 -D_POSIX=1 -DLINUX=1 -DLINUX64=1 -DLINUXSTEAMRT64=1 -DPOSIX=1 -DPROJECTDIR=/home/lwss/Documents/cstrike15_src/vscript -DVPCGAME=csgo -DVPCGAMECAPS=CSGO  $(addprefix -I, $(abspath ../common ../public ../public/tier0 ../public/tier1 ../thirdparty/SDL2 ./languages/squirrel/include ./languages/squirrel/sqplus ./languages/lua/lua-5.1.4/src ./languages/squirrel/include ./languages/squirrel/sqplus ))) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/sqcompiler.o

$(OBJ_DIR)/sqdebug.o: languages/squirrel/squirrel/sqdebug.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/sqdebug.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, -DVPC -DCSTRIKE_REL_BUILD=1 -DRAD_TELEMETRY_DISABLED -DDEBUG -D_DEBUG -DGNUC -DPOSIX -DCOMPILER_GCC -DMEMOVERRIDE_MODULE=vscript -D_DLL_EXT=_client.so -D_LINUX -DLINUX -DPOSIX -D_POSIX -DDLLNAME=vscript -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DUSE_SDL -DCSTRIKE15 -DVSCRIPT_DLL_EXPORT -DLUA_MOD_CASE_INSENSITIVE -DPROTECTED_THINGS_DISABLE -DVSCRIPT_DLL_EXPORT -D_DLL_EXT=_client.so -D_DLL_PREFIX=lib -D_EXTERNAL_DLL_EXT=.so -D_LINUX=1 -D_LINUXSTEAMRT64=1 -D_POSIX=1 -DLINUX=1 -DLINUX64=1 -DLINUXSTEAMRT64=1 -DPOSIX=1 -DPROJECTDIR=/home/lwss/Documents/cstrike15_src/vscript -DVPCGAME=csgo -DVPCGAMECAPS=CSGO  $(addprefix -I, $(abspath ../common ../public ../public/tier0 ../public/tier1 ../thirdparty/SDL2 ./languages/squirrel/include ./languages/squirrel/sqplus ./languages/lua/lua-5.1.4/src ./languages/squirrel/include ./languages/squirrel/sqplus ))) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/sqdebug.o

$(OBJ_DIR)/sqfuncstate.o: languages/squirrel/squirrel/sqfuncstate.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/sqfuncstate.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, -DVPC -DCSTRIKE_REL_BUILD=1 -DRAD_TELEMETRY_DISABLED -DDEBUG -D_DEBUG -DGNUC -DPOSIX -DCOMPILER_GCC -DMEMOVERRIDE_MODULE=vscript -D_DLL_EXT=_client.so -D_LINUX -DLINUX -DPOSIX -D_POSIX -DDLLNAME=vscript -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DUSE_SDL -DCSTRIKE15 -DVSCRIPT_DLL_EXPORT -DLUA_MOD_CASE_INSENSITIVE -DPROTECTED_THINGS_DISABLE -DVSCRIPT_DLL_EXPORT -D_DLL_EXT=_client.so -D_DLL_PREFIX=lib -D_EXTERNAL_DLL_EXT=.so -D_LINUX=1 -D_LINUXSTEAMRT64=1 -D_POSIX=1 -DLINUX=1 -DLINUX64=1 -DLINUXSTEAMRT64=1 -DPOSIX=1 -DPROJECTDIR=/home/lwss/Documents/cstrike15_src/vscript -DVPCGAME=csgo -DVPCGAMECAPS=CSGO  $(addprefix -I, $(abspath ../common ../public ../public/tier0 ../public/tier1 ../thirdparty/SDL2 ./languages/squirrel/include ./languages/squirrel/sqplus ./languages/lua/lua-5.1.4/src ./languages/squirrel/include ./languages/squirrel/sqplus ))) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/sqfuncstate.o

$(OBJ_DIR)/sqlexer.o: languages/squirrel/squirrel/sqlexer.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/sqlexer.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, -DVPC -DCSTRIKE_REL_BUILD=1 -DRAD_TELEMETRY_DISABLED -DDEBUG -D_DEBUG -DGNUC -DPOSIX -DCOMPILER_GCC -DMEMOVERRIDE_MODULE=vscript -D_DLL_EXT=_client.so -D_LINUX -DLINUX -DPOSIX -D_POSIX -DDLLNAME=vscript -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DUSE_SDL -DCSTRIKE15 -DVSCRIPT_DLL_EXPORT -DLUA_MOD_CASE_INSENSITIVE -DPROTECTED_THINGS_DISABLE -DVSCRIPT_DLL_EXPORT -D_DLL_EXT=_client.so -D_DLL_PREFIX=lib -D_EXTERNAL_DLL_EXT=.so -D_LINUX=1 -D_LINUXSTEAMRT64=1 -D_POSIX=1 -DLINUX=1 -DLINUX64=1 -DLINUXSTEAMRT64=1 -DPOSIX=1 -DPROJECTDIR=/home/lwss/Documents/cstrike15_src/vscript -DVPCGAME=csgo -DVPCGAMECAPS=CSGO  $(addprefix -I, $(abspath ../common ../public ../public/tier0 ../public/tier1 ../thirdparty/SDL2 ./languages/squirrel/include ./languages/squirrel/sqplus ./languages/lua/lua-5.1.4/src ./languages/squirrel/include ./languages/squirrel/sqplus ))) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/sqlexer.o

$(OBJ_DIR)/sqmem.o: languages/squirrel/squirrel/sqmem.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/sqmem.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, -DVPC -DCSTRIKE_REL_BUILD=1 -DRAD_TELEMETRY_DISABLED -DDEBUG -D_DEBUG -DGNUC -DPOSIX -DCOMPILER_GCC -DMEMOVERRIDE_MODULE=vscript -D_DLL_EXT=_client.so -D_LINUX -DLINUX -DPOSIX -D_POSIX -DDLLNAME=vscript -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DUSE_SDL -DCSTRIKE15 -DVSCRIPT_DLL_EXPORT -DLUA_MOD_CASE_INSENSITIVE -DPROTECTED_THINGS_DISABLE -DVSCRIPT_DLL_EXPORT -D_DLL_EXT=_client.so -D_DLL_PREFIX=lib -D_EXTERNAL_DLL_EXT=.so -D_LINUX=1 -D_LINUXSTEAMRT64=1 -D_POSIX=1 -DLINUX=1 -DLINUX64=1 -DLINUXSTEAMRT64=1 -DPOSIX=1 -DPROJECTDIR=/home/lwss/Documents/cstrike15_src/vscript -DVPCGAME=csgo -DVPCGAMECAPS=CSGO  $(addprefix -I, $(abspath ../common ../public ../public/tier0 ../public/tier1 ../thirdparty/SDL2 ./languages/squirrel/include ./languages/squirrel/sqplus ./languages/lua/lua-5.1.4/src ./languages/squirrel/include ./languages/squirrel/sqplus ))) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/sqmem.o

$(OBJ_DIR)/sqobject.o: languages/squirrel/squirrel/sqobject.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/sqobject.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, -DVPC -DCSTRIKE_REL_BUILD=1 -DRAD_TELEMETRY_DISABLED -DDEBUG -D_DEBUG -DGNUC -DPOSIX -DCOMPILER_GCC -DMEMOVERRIDE_MODULE=vscript -D_DLL_EXT=_client.so -D_LINUX -DLINUX -DPOSIX -D_POSIX -DDLLNAME=vscript -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DUSE_SDL -DCSTRIKE15 -DVSCRIPT_DLL_EXPORT -DLUA_MOD_CASE_INSENSITIVE -DPROTECTED_THINGS_DISABLE -DVSCRIPT_DLL_EXPORT -D_DLL_EXT=_client.so -D_DLL_PREFIX=lib -D_EXTERNAL_DLL_EXT=.so -D_LINUX=1 -D_LINUXSTEAMRT64=1 -D_POSIX=1 -DLINUX=1 -DLINUX64=1 -DLINUXSTEAMRT64=1 -DPOSIX=1 -DPROJECTDIR=/home/lwss/Documents/cstrike15_src/vscript -DVPCGAME=csgo -DVPCGAMECAPS=CSGO  $(addprefix -I, $(abspath ../common ../public ../public/tier0 ../public/tier1 ../thirdparty/SDL2 ./languages/squirrel/include ./languages/squirrel/sqplus ./languages/lua/lua-5.1.4/src ./languages/squirrel/include ./languages/squirrel/sqplus ))) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/sqobject.o

$(OBJ_DIR)/sqstate.o: languages/squirrel/squirrel/sqstate.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/sqstate.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, -DVPC -DCSTRIKE_REL_BUILD=1 -DRAD_TELEMETRY_DISABLED -DDEBUG -D_DEBUG -DGNUC -DPOSIX -DCOMPILER_GCC -DMEMOVERRIDE_MODULE=vscript -D_DLL_EXT=_client.so -D_LINUX -DLINUX -DPOSIX -D_POSIX -DDLLNAME=vscript -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DUSE_SDL -DCSTRIKE15 -DVSCRIPT_DLL_EXPORT -DLUA_MOD_CASE_INSENSITIVE -DPROTECTED_THINGS_DISABLE -DVSCRIPT_DLL_EXPORT -D_DLL_EXT=_client.so -D_DLL_PREFIX=lib -D_EXTERNAL_DLL_EXT=.so -D_LINUX=1 -D_LINUXSTEAMRT64=1 -D_POSIX=1 -DLINUX=1 -DLINUX64=1 -DLINUXSTEAMRT64=1 -DPOSIX=1 -DPROJECTDIR=/home/lwss/Documents/cstrike15_src/vscript -DVPCGAME=csgo -DVPCGAMECAPS=CSGO  $(addprefix -I, $(abspath ../common ../public ../public/tier0 ../public/tier1 ../thirdparty/SDL2 ./languages/squirrel/include ./languages/squirrel/sqplus ./languages/lua/lua-5.1.4/src ./languages/squirrel/include ./languages/squirrel/sqplus ))) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/sqstate.o

$(OBJ_DIR)/sqtable.o: languages/squirrel/squirrel/sqtable.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/sqtable.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, -DVPC -DCSTRIKE_REL_BUILD=1 -DRAD_TELEMETRY_DISABLED -DDEBUG -D_DEBUG -DGNUC -DPOSIX -DCOMPILER_GCC -DMEMOVERRIDE_MODULE=vscript -D_DLL_EXT=_client.so -D_LINUX -DLINUX -DPOSIX -D_POSIX -DDLLNAME=vscript -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DUSE_SDL -DCSTRIKE15 -DVSCRIPT_DLL_EXPORT -DLUA_MOD_CASE_INSENSITIVE -DPROTECTED_THINGS_DISABLE -DVSCRIPT_DLL_EXPORT -D_DLL_EXT=_client.so -D_DLL_PREFIX=lib -D_EXTERNAL_DLL_EXT=.so -D_LINUX=1 -D_LINUXSTEAMRT64=1 -D_POSIX=1 -DLINUX=1 -DLINUX64=1 -DLINUXSTEAMRT64=1 -DPOSIX=1 -DPROJECTDIR=/home/lwss/Documents/cstrike15_src/vscript -DVPCGAME=csgo -DVPCGAMECAPS=CSGO  $(addprefix -I, $(abspath ../common ../public ../public/tier0 ../public/tier1 ../thirdparty/SDL2 ./languages/squirrel/include ./languages/squirrel/sqplus ./languages/lua/lua-5.1.4/src ./languages/squirrel/include ./languages/squirrel/sqplus ))) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/sqtable.o

$(OBJ_DIR)/sqvm.o: languages/squirrel/squirrel/sqvm.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/sqvm.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, -DVPC -DCSTRIKE_REL_BUILD=1 -DRAD_TELEMETRY_DISABLED -DDEBUG -D_DEBUG -DGNUC -DPOSIX -DCOMPILER_GCC -DMEMOVERRIDE_MODULE=vscript -D_DLL_EXT=_client.so -D_LINUX -DLINUX -DPOSIX -D_POSIX -DDLLNAME=vscript -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DUSE_SDL -DCSTRIKE15 -DVSCRIPT_DLL_EXPORT -DLUA_MOD_CASE_INSENSITIVE -DPROTECTED_THINGS_DISABLE -DVSCRIPT_DLL_EXPORT -D_DLL_EXT=_client.so -D_DLL_PREFIX=lib -D_EXTERNAL_DLL_EXT=.so -D_LINUX=1 -D_LINUXSTEAMRT64=1 -D_POSIX=1 -DLINUX=1 -DLINUX64=1 -DLINUXSTEAMRT64=1 -DPOSIX=1 -DPROJECTDIR=/home/lwss/Documents/cstrike15_src/vscript -DVPCGAME=csgo -DVPCGAMECAPS=CSGO  $(addprefix -I, $(abspath ../common ../public ../public/tier0 ../public/tier1 ../thirdparty/SDL2 ./languages/squirrel/include ./languages/squirrel/sqplus ./languages/lua/lua-5.1.4/src ./languages/squirrel/include ./languages/squirrel/sqplus ))) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/sqvm.o

$(OBJ_DIR)/sqrdbg.o: languages/squirrel/sqdbg/sqrdbg.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/sqrdbg.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, -DVPC -DCSTRIKE_REL_BUILD=1 -DRAD_TELEMETRY_DISABLED -DDEBUG -D_DEBUG -DGNUC -DPOSIX -DCOMPILER_GCC -DMEMOVERRIDE_MODULE=vscript -D_DLL_EXT=_client.so -D_LINUX -DLINUX -DPOSIX -D_POSIX -DDLLNAME=vscript -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DUSE_SDL -DCSTRIKE15 -DVSCRIPT_DLL_EXPORT -DLUA_MOD_CASE_INSENSITIVE -DPROTECTED_THINGS_DISABLE -DVSCRIPT_DLL_EXPORT -D_DLL_EXT=_client.so -D_DLL_PREFIX=lib -D_EXTERNAL_DLL_EXT=.so -D_LINUX=1 -D_LINUXSTEAMRT64=1 -D_POSIX=1 -DLINUX=1 -DLINUX64=1 -DLINUXSTEAMRT64=1 -DPOSIX=1 -DPROJECTDIR=/home/lwss/Documents/cstrike15_src/vscript -DVPCGAME=csgo -DVPCGAMECAPS=CSGO  $(addprefix -I, $(abspath ../common ../public ../public/tier0 ../public/tier1 ../thirdparty/SDL2 ./languages/squirrel/include ./languages/squirrel/sqplus ./languages/lua/lua-5.1.4/src ./languages/squirrel/include ./languages/squirrel/sqplus ))) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/sqrdbg.o

$(OBJ_DIR)/sqdbgserver.o: languages/squirrel/sqdbg/sqdbgserver.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/sqdbgserver.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, -DVPC -DCSTRIKE_REL_BUILD=1 -DRAD_TELEMETRY_DISABLED -DDEBUG -D_DEBUG -DGNUC -DPOSIX -DCOMPILER_GCC -DMEMOVERRIDE_MODULE=vscript -D_DLL_EXT=_client.so -D_LINUX -DLINUX -DPOSIX -D_POSIX -DDLLNAME=vscript -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DUSE_SDL -DCSTRIKE15 -DVSCRIPT_DLL_EXPORT -DLUA_MOD_CASE_INSENSITIVE -DPROTECTED_THINGS_DISABLE -DVSCRIPT_DLL_EXPORT -D_DLL_EXT=_client.so -D_DLL_PREFIX=lib -D_EXTERNAL_DLL_EXT=.so -D_LINUX=1 -D_LINUXSTEAMRT64=1 -D_POSIX=1 -DLINUX=1 -DLINUX64=1 -DLINUXSTEAMRT64=1 -DPOSIX=1 -DPROJECTDIR=/home/lwss/Documents/cstrike15_src/vscript -DVPCGAME=csgo -DVPCGAMECAPS=CSGO  $(addprefix -I, $(abspath ../common ../public ../public/tier0 ../public/tier1 ../thirdparty/SDL2 ./languages/squirrel/include ./languages/squirrel/sqplus ./languages/lua/lua-5.1.4/src ./languages/squirrel/include ./languages/squirrel/sqplus ))) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/sqdbgserver.o

$(OBJ_DIR)/sqstdaux.o: languages/squirrel/sqstdlib/sqstdaux.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/sqstdaux.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, -DVPC -DCSTRIKE_REL_BUILD=1 -DRAD_TELEMETRY_DISABLED -DDEBUG -D_DEBUG -DGNUC -DPOSIX -DCOMPILER_GCC -DMEMOVERRIDE_MODULE=vscript -D_DLL_EXT=_client.so -D_LINUX -DLINUX -DPOSIX -D_POSIX -DDLLNAME=vscript -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DUSE_SDL -DCSTRIKE15 -DVSCRIPT_DLL_EXPORT -DLUA_MOD_CASE_INSENSITIVE -DPROTECTED_THINGS_DISABLE -DVSCRIPT_DLL_EXPORT -D_DLL_EXT=_client.so -D_DLL_PREFIX=lib -D_EXTERNAL_DLL_EXT=.so -D_LINUX=1 -D_LINUXSTEAMRT64=1 -D_POSIX=1 -DLINUX=1 -DLINUX64=1 -DLINUXSTEAMRT64=1 -DPOSIX=1 -DPROJECTDIR=/home/lwss/Documents/cstrike15_src/vscript -DVPCGAME=csgo -DVPCGAMECAPS=CSGO  $(addprefix -I, $(abspath ../common ../public ../public/tier0 ../public/tier1 ../thirdparty/SDL2 ./languages/squirrel/include ./languages/squirrel/sqplus ./languages/lua/lua-5.1.4/src ./languages/squirrel/include ./languages/squirrel/sqplus ))) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/sqstdaux.o

$(OBJ_DIR)/sqstdblob.o: languages/squirrel/sqstdlib/sqstdblob.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/sqstdblob.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, -DVPC -DCSTRIKE_REL_BUILD=1 -DRAD_TELEMETRY_DISABLED -DDEBUG -D_DEBUG -DGNUC -DPOSIX -DCOMPILER_GCC -DMEMOVERRIDE_MODULE=vscript -D_DLL_EXT=_client.so -D_LINUX -DLINUX -DPOSIX -D_POSIX -DDLLNAME=vscript -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DUSE_SDL -DCSTRIKE15 -DVSCRIPT_DLL_EXPORT -DLUA_MOD_CASE_INSENSITIVE -DPROTECTED_THINGS_DISABLE -DVSCRIPT_DLL_EXPORT -D_DLL_EXT=_client.so -D_DLL_PREFIX=lib -D_EXTERNAL_DLL_EXT=.so -D_LINUX=1 -D_LINUXSTEAMRT64=1 -D_POSIX=1 -DLINUX=1 -DLINUX64=1 -DLINUXSTEAMRT64=1 -DPOSIX=1 -DPROJECTDIR=/home/lwss/Documents/cstrike15_src/vscript -DVPCGAME=csgo -DVPCGAMECAPS=CSGO  $(addprefix -I, $(abspath ../common ../public ../public/tier0 ../public/tier1 ../thirdparty/SDL2 ./languages/squirrel/include ./languages/squirrel/sqplus ./languages/lua/lua-5.1.4/src ./languages/squirrel/include ./languages/squirrel/sqplus ))) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/sqstdblob.o

$(OBJ_DIR)/sqstdmath.o: languages/squirrel/sqstdlib/sqstdmath.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/sqstdmath.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, -DVPC -DCSTRIKE_REL_BUILD=1 -DRAD_TELEMETRY_DISABLED -DDEBUG -D_DEBUG -DGNUC -DPOSIX -DCOMPILER_GCC -DMEMOVERRIDE_MODULE=vscript -D_DLL_EXT=_client.so -D_LINUX -DLINUX -DPOSIX -D_POSIX -DDLLNAME=vscript -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DUSE_SDL -DCSTRIKE15 -DVSCRIPT_DLL_EXPORT -DLUA_MOD_CASE_INSENSITIVE -DPROTECTED_THINGS_DISABLE -DVSCRIPT_DLL_EXPORT -D_DLL_EXT=_client.so -D_DLL_PREFIX=lib -D_EXTERNAL_DLL_EXT=.so -D_LINUX=1 -D_LINUXSTEAMRT64=1 -D_POSIX=1 -DLINUX=1 -DLINUX64=1 -DLINUXSTEAMRT64=1 -DPOSIX=1 -DPROJECTDIR=/home/lwss/Documents/cstrike15_src/vscript -DVPCGAME=csgo -DVPCGAMECAPS=CSGO  $(addprefix -I, $(abspath ../common ../public ../public/tier0 ../public/tier1 ../thirdparty/SDL2 ./languages/squirrel/include ./languages/squirrel/sqplus ./languages/lua/lua-5.1.4/src ./languages/squirrel/include ./languages/squirrel/sqplus ))) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/sqstdmath.o

$(OBJ_DIR)/sqstdrex.o: languages/squirrel/sqstdlib/sqstdrex.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/sqstdrex.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, -DVPC -DCSTRIKE_REL_BUILD=1 -DRAD_TELEMETRY_DISABLED -DDEBUG -D_DEBUG -DGNUC -DPOSIX -DCOMPILER_GCC -DMEMOVERRIDE_MODULE=vscript -D_DLL_EXT=_client.so -D_LINUX -DLINUX -DPOSIX -D_POSIX -DDLLNAME=vscript -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DUSE_SDL -DCSTRIKE15 -DVSCRIPT_DLL_EXPORT -DLUA_MOD_CASE_INSENSITIVE -DPROTECTED_THINGS_DISABLE -DVSCRIPT_DLL_EXPORT -D_DLL_EXT=_client.so -D_DLL_PREFIX=lib -D_EXTERNAL_DLL_EXT=.so -D_LINUX=1 -D_LINUXSTEAMRT64=1 -D_POSIX=1 -DLINUX=1 -DLINUX64=1 -DLINUXSTEAMRT64=1 -DPOSIX=1 -DPROJECTDIR=/home/lwss/Documents/cstrike15_src/vscript -DVPCGAME=csgo -DVPCGAMECAPS=CSGO  $(addprefix -I, $(abspath ../common ../public ../public/tier0 ../public/tier1 ../thirdparty/SDL2 ./languages/squirrel/include ./languages/squirrel/sqplus ./languages/lua/lua-5.1.4/src ./languages/squirrel/include ./languages/squirrel/sqplus ))) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/sqstdrex.o

$(OBJ_DIR)/sqstdstream.o: languages/squirrel/sqstdlib/sqstdstream.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/sqstdstream.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, -DVPC -DCSTRIKE_REL_BUILD=1 -DRAD_TELEMETRY_DISABLED -DDEBUG -D_DEBUG -DGNUC -DPOSIX -DCOMPILER_GCC -DMEMOVERRIDE_MODULE=vscript -D_DLL_EXT=_client.so -D_LINUX -DLINUX -DPOSIX -D_POSIX -DDLLNAME=vscript -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DUSE_SDL -DCSTRIKE15 -DVSCRIPT_DLL_EXPORT -DLUA_MOD_CASE_INSENSITIVE -DPROTECTED_THINGS_DISABLE -DVSCRIPT_DLL_EXPORT -D_DLL_EXT=_client.so -D_DLL_PREFIX=lib -D_EXTERNAL_DLL_EXT=.so -D_LINUX=1 -D_LINUXSTEAMRT64=1 -D_POSIX=1 -DLINUX=1 -DLINUX64=1 -DLINUXSTEAMRT64=1 -DPOSIX=1 -DPROJECTDIR=/home/lwss/Documents/cstrike15_src/vscript -DVPCGAME=csgo -DVPCGAMECAPS=CSGO  $(addprefix -I, $(abspath ../common ../public ../public/tier0 ../public/tier1 ../thirdparty/SDL2 ./languages/squirrel/include ./languages/squirrel/sqplus ./languages/lua/lua-5.1.4/src ./languages/squirrel/include ./languages/squirrel/sqplus ))) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/sqstdstream.o

$(OBJ_DIR)/sqstdstring.o: languages/squirrel/sqstdlib/sqstdstring.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/sqstdstring.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, -DVPC -DCSTRIKE_REL_BUILD=1 -DRAD_TELEMETRY_DISABLED -DDEBUG -D_DEBUG -DGNUC -DPOSIX -DCOMPILER_GCC -DMEMOVERRIDE_MODULE=vscript -D_DLL_EXT=_client.so -D_LINUX -DLINUX -DPOSIX -D_POSIX -DDLLNAME=vscript -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DUSE_SDL -DCSTRIKE15 -DVSCRIPT_DLL_EXPORT -DLUA_MOD_CASE_INSENSITIVE -DPROTECTED_THINGS_DISABLE -DVSCRIPT_DLL_EXPORT -D_DLL_EXT=_client.so -D_DLL_PREFIX=lib -D_EXTERNAL_DLL_EXT=.so -D_LINUX=1 -D_LINUXSTEAMRT64=1 -D_POSIX=1 -DLINUX=1 -DLINUX64=1 -DLINUXSTEAMRT64=1 -DPOSIX=1 -DPROJECTDIR=/home/lwss/Documents/cstrike15_src/vscript -DVPCGAME=csgo -DVPCGAMECAPS=CSGO  $(addprefix -I, $(abspath ../common ../public ../public/tier0 ../public/tier1 ../thirdparty/SDL2 ./languages/squirrel/include ./languages/squirrel/sqplus ./languages/lua/lua-5.1.4/src ./languages/squirrel/include ./languages/squirrel/sqplus ))) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/sqstdstring.o

$(OBJ_DIR)/SqPlus.o: languages/squirrel/sqplus/SqPlus.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/SqPlus.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, -DVPC -DCSTRIKE_REL_BUILD=1 -DRAD_TELEMETRY_DISABLED -DDEBUG -D_DEBUG -DGNUC -DPOSIX -DCOMPILER_GCC -DMEMOVERRIDE_MODULE=vscript -D_DLL_EXT=_client.so -D_LINUX -DLINUX -DPOSIX -D_POSIX -DDLLNAME=vscript -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DUSE_SDL -DCSTRIKE15 -DVSCRIPT_DLL_EXPORT -DLUA_MOD_CASE_INSENSITIVE -DPROTECTED_THINGS_DISABLE -DVSCRIPT_DLL_EXPORT -D_DLL_EXT=_client.so -D_DLL_PREFIX=lib -D_EXTERNAL_DLL_EXT=.so -D_LINUX=1 -D_LINUXSTEAMRT64=1 -D_POSIX=1 -DLINUX=1 -DLINUX64=1 -DLINUXSTEAMRT64=1 -DPOSIX=1 -DPROJECTDIR=/home/lwss/Documents/cstrike15_src/vscript -DVPCGAME=csgo -DVPCGAMECAPS=CSGO  $(addprefix -I, $(abspath ../common ../public ../public/tier0 ../public/tier1 ../thirdparty/SDL2 ./languages/squirrel/include ./languages/squirrel/sqplus ./languages/lua/lua-5.1.4/src ./languages/squirrel/include ./languages/squirrel/sqplus ))) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/SqPlus.o

$(OBJ_DIR)/SquirrelBindingsUtils.o: languages/squirrel/sqplus/SquirrelBindingsUtils.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/SquirrelBindingsUtils.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, -DVPC -DCSTRIKE_REL_BUILD=1 -DRAD_TELEMETRY_DISABLED -DDEBUG -D_DEBUG -DGNUC -DPOSIX -DCOMPILER_GCC -DMEMOVERRIDE_MODULE=vscript -D_DLL_EXT=_client.so -D_LINUX -DLINUX -DPOSIX -D_POSIX -DDLLNAME=vscript -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DUSE_SDL -DCSTRIKE15 -DVSCRIPT_DLL_EXPORT -DLUA_MOD_CASE_INSENSITIVE -DPROTECTED_THINGS_DISABLE -DVSCRIPT_DLL_EXPORT -D_DLL_EXT=_client.so -D_DLL_PREFIX=lib -D_EXTERNAL_DLL_EXT=.so -D_LINUX=1 -D_LINUXSTEAMRT64=1 -D_POSIX=1 -DLINUX=1 -DLINUX64=1 -DLINUXSTEAMRT64=1 -DPOSIX=1 -DPROJECTDIR=/home/lwss/Documents/cstrike15_src/vscript -DVPCGAME=csgo -DVPCGAMECAPS=CSGO  $(addprefix -I, $(abspath ../common ../public ../public/tier0 ../public/tier1 ../thirdparty/SDL2 ./languages/squirrel/include ./languages/squirrel/sqplus ./languages/lua/lua-5.1.4/src ./languages/squirrel/include ./languages/squirrel/sqplus ))) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/SquirrelBindingsUtils.o

$(OBJ_DIR)/SquirrelObject.o: languages/squirrel/sqplus/SquirrelObject.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/SquirrelObject.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, -DVPC -DCSTRIKE_REL_BUILD=1 -DRAD_TELEMETRY_DISABLED -DDEBUG -D_DEBUG -DGNUC -DPOSIX -DCOMPILER_GCC -DMEMOVERRIDE_MODULE=vscript -D_DLL_EXT=_client.so -D_LINUX -DLINUX -DPOSIX -D_POSIX -DDLLNAME=vscript -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DUSE_SDL -DCSTRIKE15 -DVSCRIPT_DLL_EXPORT -DLUA_MOD_CASE_INSENSITIVE -DPROTECTED_THINGS_DISABLE -DVSCRIPT_DLL_EXPORT -D_DLL_EXT=_client.so -D_DLL_PREFIX=lib -D_EXTERNAL_DLL_EXT=.so -D_LINUX=1 -D_LINUXSTEAMRT64=1 -D_POSIX=1 -DLINUX=1 -DLINUX64=1 -DLINUXSTEAMRT64=1 -DPOSIX=1 -DPROJECTDIR=/home/lwss/Documents/cstrike15_src/vscript -DVPCGAME=csgo -DVPCGAMECAPS=CSGO  $(addprefix -I, $(abspath ../common ../public ../public/tier0 ../public/tier1 ../thirdparty/SDL2 ./languages/squirrel/include ./languages/squirrel/sqplus ./languages/lua/lua-5.1.4/src ./languages/squirrel/include ./languages/squirrel/sqplus ))) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/SquirrelObject.o

$(OBJ_DIR)/SquirrelVM.o: languages/squirrel/sqplus/SquirrelVM.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/SquirrelVM.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, -DVPC -DCSTRIKE_REL_BUILD=1 -DRAD_TELEMETRY_DISABLED -DDEBUG -D_DEBUG -DGNUC -DPOSIX -DCOMPILER_GCC -DMEMOVERRIDE_MODULE=vscript -D_DLL_EXT=_client.so -D_LINUX -DLINUX -DPOSIX -D_POSIX -DDLLNAME=vscript -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DUSE_SDL -DCSTRIKE15 -DVSCRIPT_DLL_EXPORT -DLUA_MOD_CASE_INSENSITIVE -DPROTECTED_THINGS_DISABLE -DVSCRIPT_DLL_EXPORT -D_DLL_EXT=_client.so -D_DLL_PREFIX=lib -D_EXTERNAL_DLL_EXT=.so -D_LINUX=1 -D_LINUXSTEAMRT64=1 -D_POSIX=1 -DLINUX=1 -DLINUX64=1 -DLINUXSTEAMRT64=1 -DPOSIX=1 -DPROJECTDIR=/home/lwss/Documents/cstrike15_src/vscript -DVPCGAME=csgo -DVPCGAMECAPS=CSGO  $(addprefix -I, $(abspath ../common ../public ../public/tier0 ../public/tier1 ../thirdparty/SDL2 ./languages/squirrel/include ./languages/squirrel/sqplus ./languages/lua/lua-5.1.4/src ./languages/squirrel/include ./languages/squirrel/sqplus ))) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/SquirrelVM.o

endif # (CFG=debug)




















################################################################################
#
# CFG=release
#
################################################################################

ifeq "$(CFG)" "release"

GCC_ExtraCompilerFlags=
GCC_ExtraCxxCompilerFlags=
GCC_ExtraLinkerFlags=
DisableLinkerDeadCodeElimination=
SymbolVisibility=hidden
TreatWarningsAsErrors=false
OptimizerLevel=-gdwarf-4 -g2 $(OptimizerLevel_CompilerSpecific)
PrecompiledHeaderInclude=
SystemLibraries=
DLL_EXT=_client.so
SYM_EXT=.dbg
DEVTOOLS := ../devtools
MAKEFILE_BASE := $(DEVTOOLS)/makefile_base_posix.mak
COMPILE_DEPENDANT_MAKEFILES := vscript_linux64.mak $(MAKEFILE_BASE)
FORCEINCLUDES= 
DEFINES += -DVPC -DCSTRIKE_REL_BUILD=1 -DRAD_TELEMETRY_DISABLED -DNDEBUG -D_GLIBCXX_USE_CXX11_ABI=0 -DGNUC -DPOSIX -DCOMPILER_GCC -DMEMOVERRIDE_MODULE=vscript -D_DLL_EXT=_client.so -D_LINUX -DLINUX -DPOSIX -D_POSIX -DDLLNAME=vscript -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DUSE_SDL -DCSTRIKE15 -DVSCRIPT_DLL_EXPORT -DLUA_MOD_CASE_INSENSITIVE -D_DLL_EXT=_client.so -D_DLL_PREFIX=lib -D_EXTERNAL_DLL_EXT=.so -D_LINUX=1 -D_LINUXSTEAMRT64=1 -D_POSIX=1 -DLINUX=1 -DLINUX64=1 -DLINUXSTEAMRT64=1 -DPOSIX=1 -DPROJECTDIR=/home/lwss/Documents/cstrike15_src/vscript -DVPCGAME=csgo -DVPCGAMECAPS=CSGO 
INCLUDEDIRS += ../common ../public ../public/tier0 ../public/tier1 ../thirdparty/SDL2 ./languages/squirrel/include ./languages/squirrel/sqplus ./languages/lua/lua-5.1.4/src 
CONFTYPE=dll
IMPORTLIBRARY=
OUTPUTFILE=$(OBJ_DIR)/vscript_client.so
GAMEOUTPUTFILE=../../game/bin/linux64/vscript_client.so

CPPFILES= \
    ../public/tier0/memoverride.cpp \
    vscript.cpp \
    languages/squirrel/vsquirrel/vsquirrel.cpp \
    languages/squirrel/squirrel/sqapi.cpp \
    languages/squirrel/squirrel/sqbaselib.cpp \
    languages/squirrel/squirrel/sqclass.cpp \
    languages/squirrel/squirrel/sqcompiler.cpp \
    languages/squirrel/squirrel/sqdebug.cpp \
    languages/squirrel/squirrel/sqfuncstate.cpp \
    languages/squirrel/squirrel/sqlexer.cpp \
    languages/squirrel/squirrel/sqmem.cpp \
    languages/squirrel/squirrel/sqobject.cpp \
    languages/squirrel/squirrel/sqstate.cpp \
    languages/squirrel/squirrel/sqtable.cpp \
    languages/squirrel/squirrel/sqvm.cpp \
    languages/squirrel/sqdbg/sqrdbg.cpp \
    languages/squirrel/sqdbg/sqdbgserver.cpp \
    languages/squirrel/sqstdlib/sqstdaux.cpp \
    languages/squirrel/sqstdlib/sqstdblob.cpp \
    languages/squirrel/sqstdlib/sqstdmath.cpp \
    languages/squirrel/sqstdlib/sqstdrex.cpp \
    languages/squirrel/sqstdlib/sqstdstream.cpp \
    languages/squirrel/sqstdlib/sqstdstring.cpp \
    languages/squirrel/sqplus/SqPlus.cpp \
    languages/squirrel/sqplus/SquirrelBindingsUtils.cpp \
    languages/squirrel/sqplus/SquirrelObject.cpp \
    languages/squirrel/sqplus/SquirrelVM.cpp

unexport CPPFILES

LIBFILES = \
    ../lib/public/linux64/tier1_client.a \
    ../lib/public/linux64/interfaces_client.a \
    ../lib/public/linux64/mathlib_client.a \
    -L../lib/public/linux64 -ltier0_client \
    -L../lib/public/linux64 -lvstdlib_client

unexport LIBFILES

LIBFILENAMES = \
    ../lib/public/linux64/libtier0_client.so \
    ../lib/public/linux64/tier1_client.a \
    ../lib/public/linux64/interfaces_client.a \
    ../lib/public/linux64/libvstdlib_client.so \
    ../lib/public/linux64/mathlib_client.a

unexport LIBFILENAMES

ALL_CUSTOM_BUILD_TOOLS = \
    $(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/sentinels/languages_dir_squirrel_dir_vsquirrel_dir_init_dot_nut

unexport ALL_CUSTOM_BUILD_TOOLS

ALL_CUSTOM_BUILD_TOOL_DEPENDENCIES = \
    languages/squirrel/vsquirrel/init.nut \
    ../vpc_scripts/vpc_trivial_dependency.txt

unexport ALL_CUSTOM_BUILD_TOOL_DEPENDENCIES

ALL_CUSTOM_BUILD_TOOL_SCRIPTS = \
    _vpc_/generated_scripts_vscript/linux64/Release/custom_build_tools/languages_dir_squirrel_dir_vsquirrel_dir_init_dot_nut.sh

unexport ALL_CUSTOM_BUILD_TOOL_SCRIPTS

ALL_CUSTOM_BUILD_TOOL_OUTPUTS = \
    languages/squirrel/vsquirrel/init_nut.h

unexport ALL_CUSTOM_BUILD_TOOL_OUTPUTS

ALL_DEPGEN_FILES = \
    $(OBJ_DIR)/memoverride.P \
    $(OBJ_DIR)/vscript.P \
    $(OBJ_DIR)/vsquirrel.P \
    $(OBJ_DIR)/sqapi.P \
    $(OBJ_DIR)/sqbaselib.P \
    $(OBJ_DIR)/sqclass.P \
    $(OBJ_DIR)/sqcompiler.P \
    $(OBJ_DIR)/sqdebug.P \
    $(OBJ_DIR)/sqfuncstate.P \
    $(OBJ_DIR)/sqlexer.P \
    $(OBJ_DIR)/sqmem.P \
    $(OBJ_DIR)/sqobject.P \
    $(OBJ_DIR)/sqstate.P \
    $(OBJ_DIR)/sqtable.P \
    $(OBJ_DIR)/sqvm.P \
    $(OBJ_DIR)/sqrdbg.P \
    $(OBJ_DIR)/sqdbgserver.P \
    $(OBJ_DIR)/sqstdaux.P \
    $(OBJ_DIR)/sqstdblob.P \
    $(OBJ_DIR)/sqstdmath.P \
    $(OBJ_DIR)/sqstdrex.P \
    $(OBJ_DIR)/sqstdstream.P \
    $(OBJ_DIR)/sqstdstring.P \
    $(OBJ_DIR)/SqPlus.P \
    $(OBJ_DIR)/SquirrelBindingsUtils.P \
    $(OBJ_DIR)/SquirrelObject.P \
    $(OBJ_DIR)/SquirrelVM.P

unexport ALL_DEPGEN_FILES


#
# Include the base makefile now.
#
include $(MAKEFILE_BASE)


#
# Create sentinel directories
#
$(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/_vpc_create_dirs: vscript_linux64.mak | $(OBJ_DIR)/_create_dir
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) create custom build tools dir start
	$(QUIET_PREFIX) $(MKDIR) -p $(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/locks $(QUIET_ECHO_POSTFIX)
	$(QUIET_PREFIX) $(MKDIR) -p $(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/ranthisbuild $(QUIET_ECHO_POSTFIX)
	$(QUIET_PREFIX) $(MKDIR) -p $(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/sentinels $(QUIET_ECHO_POSTFIX)
	$(QUIET_PREFIX) $(TOUCH) $(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/_vpc_create_dirs


#
# Custom Build Tool "init.nut produces init_nut.h" for file "languages/squirrel/vsquirrel/init.nut"
#
DEPENDENCIES_FOR_BUILD_TOOL_languages_dir_squirrel_dir_vsquirrel_dir_init_dot_nut = \
    languages/squirrel/vsquirrel/init.nut \
    ../vpc_scripts/vpc_trivial_dependency.txt

unexport DEPENDENCIES_FOR_BUILD_TOOL_languages_dir_squirrel_dir_vsquirrel_dir_init_dot_nut

ORDER_ONLY_DEPENDENCIES_FOR_BUILD_TOOL_languages_dir_squirrel_dir_vsquirrel_dir_init_dot_nut =

unexport ORDER_ONLY_DEPENDENCIES_FOR_BUILD_TOOL_languages_dir_squirrel_dir_vsquirrel_dir_init_dot_nut

CUSTOM_BUILD_TOOL_ACTION_languages_dir_squirrel_dir_vsquirrel_dir_init_dot_nut = \
    { \
        $(ECHO) "init.nut produces init_nut.h" && \
        { $(SHELL) _vpc_/generated_scripts_vscript/linux64/Release/custom_build_tools/languages_dir_squirrel_dir_vsquirrel_dir_init_dot_nut.sh $(PROCESS_COMPILER_OUTPUT); } && \
            $(TOUCH) "$(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/sentinels/languages_dir_squirrel_dir_vsquirrel_dir_init_dot_nut" || \
            { $(ECHO) "Error executing custom build tool \"_vpc_/generated_scripts_vscript/linux64/Release/custom_build_tools/languages_dir_squirrel_dir_vsquirrel_dir_init_dot_nut.sh\""; false }; }; \
    }

unexport CUSTOM_BUILD_TOOL_ACTION_languages_dir_squirrel_dir_vsquirrel_dir_init_dot_nut

OUTPUTS_FOR_BUILD_TOOL_languages_dir_squirrel_dir_vsquirrel_dir_init_dot_nut = \
    languages/squirrel/vsquirrel/init_nut.h

unexport OUTPUTS_FOR_BUILD_TOOL_languages_dir_squirrel_dir_vsquirrel_dir_init_dot_nut

POTENTIAL_OUTPUTS_FOR_BUILD_TOOL_languages_dir_squirrel_dir_vsquirrel_dir_init_dot_nut =

unexport POTENTIAL_OUTPUTS_FOR_BUILD_TOOL_languages_dir_squirrel_dir_vsquirrel_dir_init_dot_nut

_prebuild_always::
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) _prebuild_always for custom build tool languages_dir_squirrel_dir_vsquirrel_dir_init_dot_nut start
	$(QUIET_PREFIX) $(RM) -fr $(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/ranthisbuild/languages_dir_squirrel_dir_vsquirrel_dir_init_dot_nut
	$(QUIET_PREFIX) $(RM) -fr $(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/locks/languages_dir_squirrel_dir_vsquirrel_dir_init_dot_nut

$(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/sentinels/languages_dir_squirrel_dir_vsquirrel_dir_init_dot_nut $(OUTPUTS_FOR_BUILD_TOOL_languages_dir_squirrel_dir_vsquirrel_dir_init_dot_nut): _vpc_/generated_scripts_vscript/linux64/Release/custom_build_tools/languages_dir_squirrel_dir_vsquirrel_dir_init_dot_nut.sh $(DEPENDENCIES_FOR_BUILD_TOOL_languages_dir_squirrel_dir_vsquirrel_dir_init_dot_nut) | _prebuild_steps $(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/_vpc_create_dirs $(ORDER_ONLY_DEPENDENCIES_FOR_BUILD_TOOL_languages_dir_squirrel_dir_vsquirrel_dir_init_dot_nut)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) custom build tool for languages_dir_squirrel_dir_vsquirrel_dir_init_dot_nut start
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(QUIET_PREFIX) $(call RUN_RECIPE_ACTION_ONCE,"$(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/ranthisbuild/languages_dir_squirrel_dir_vsquirrel_dir_init_dot_nut","$(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/locks/languages_dir_squirrel_dir_vsquirrel_dir_init_dot_nut",$(call CUSTOM_BUILD_TOOL_ACTION_languages_dir_squirrel_dir_vsquirrel_dir_init_dot_nut))


#
# include all the depgen .P files which will include dependency information.
#
include $(wildcard $(OBJ_DIR)/memoverride.P)
include $(wildcard $(OBJ_DIR)/vscript.P)
include $(wildcard $(OBJ_DIR)/vsquirrel.P)
include $(wildcard $(OBJ_DIR)/sqapi.P)
include $(wildcard $(OBJ_DIR)/sqbaselib.P)
include $(wildcard $(OBJ_DIR)/sqclass.P)
include $(wildcard $(OBJ_DIR)/sqcompiler.P)
include $(wildcard $(OBJ_DIR)/sqdebug.P)
include $(wildcard $(OBJ_DIR)/sqfuncstate.P)
include $(wildcard $(OBJ_DIR)/sqlexer.P)
include $(wildcard $(OBJ_DIR)/sqmem.P)
include $(wildcard $(OBJ_DIR)/sqobject.P)
include $(wildcard $(OBJ_DIR)/sqstate.P)
include $(wildcard $(OBJ_DIR)/sqtable.P)
include $(wildcard $(OBJ_DIR)/sqvm.P)
include $(wildcard $(OBJ_DIR)/sqrdbg.P)
include $(wildcard $(OBJ_DIR)/sqdbgserver.P)
include $(wildcard $(OBJ_DIR)/sqstdaux.P)
include $(wildcard $(OBJ_DIR)/sqstdblob.P)
include $(wildcard $(OBJ_DIR)/sqstdmath.P)
include $(wildcard $(OBJ_DIR)/sqstdrex.P)
include $(wildcard $(OBJ_DIR)/sqstdstream.P)
include $(wildcard $(OBJ_DIR)/sqstdstring.P)
include $(wildcard $(OBJ_DIR)/SqPlus.P)
include $(wildcard $(OBJ_DIR)/SquirrelBindingsUtils.P)
include $(wildcard $(OBJ_DIR)/SquirrelObject.P)
include $(wildcard $(OBJ_DIR)/SquirrelVM.P)


#
# Compare/cache a string of compile settings to see if we need to recompile .o's
#
$(eval $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS,COMPILE_O_GLOBAL_SETTINGS,$$(call COMPILE_O_SETTINGS,$$(CFG_CPPFLAGS))))


#
# Compile rules
#
$(OBJ_DIR)/memoverride.o: ../public/tier0/memoverride.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/memoverride.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/memoverride.o

$(OBJ_DIR)/vscript.o: vscript.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/vscript.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/vscript.o

$(OBJ_DIR)/vsquirrel.o: languages/squirrel/vsquirrel/vsquirrel.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/vsquirrel.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, -DVPC -DCSTRIKE_REL_BUILD=1 -DRAD_TELEMETRY_DISABLED -DNDEBUG -D_GLIBCXX_USE_CXX11_ABI=0 -DGNUC -DPOSIX -DCOMPILER_GCC -DMEMOVERRIDE_MODULE=vscript -D_DLL_EXT=_client.so -D_LINUX -DLINUX -DPOSIX -D_POSIX -DDLLNAME=vscript -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DUSE_SDL -DCSTRIKE15 -DVSCRIPT_DLL_EXPORT -DLUA_MOD_CASE_INSENSITIVE -D_DLL_EXT=_client.so -D_DLL_PREFIX=lib -D_EXTERNAL_DLL_EXT=.so -D_LINUX=1 -D_LINUXSTEAMRT64=1 -D_POSIX=1 -DLINUX=1 -DLINUX64=1 -DLINUXSTEAMRT64=1 -DPOSIX=1 -DPROJECTDIR=/home/lwss/Documents/cstrike15_src/vscript -DVPCGAME=csgo -DVPCGAMECAPS=CSGO  $(addprefix -I, $(abspath ../common ../public ../public/tier0 ../public/tier1 ../thirdparty/SDL2 ./languages/squirrel/include ./languages/squirrel/sqplus ./languages/lua/lua-5.1.4/src ./languages/squirrel/include ./languages/squirrel/sqplus ))) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/vsquirrel.o

$(OBJ_DIR)/sqapi.o: languages/squirrel/squirrel/sqapi.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/sqapi.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, -DVPC -DCSTRIKE_REL_BUILD=1 -DRAD_TELEMETRY_DISABLED -DNDEBUG -D_GLIBCXX_USE_CXX11_ABI=0 -DGNUC -DPOSIX -DCOMPILER_GCC -DMEMOVERRIDE_MODULE=vscript -D_DLL_EXT=_client.so -D_LINUX -DLINUX -DPOSIX -D_POSIX -DDLLNAME=vscript -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DUSE_SDL -DCSTRIKE15 -DVSCRIPT_DLL_EXPORT -DLUA_MOD_CASE_INSENSITIVE -DPROTECTED_THINGS_DISABLE -DVSCRIPT_DLL_EXPORT -D_DLL_EXT=_client.so -D_DLL_PREFIX=lib -D_EXTERNAL_DLL_EXT=.so -D_LINUX=1 -D_LINUXSTEAMRT64=1 -D_POSIX=1 -DLINUX=1 -DLINUX64=1 -DLINUXSTEAMRT64=1 -DPOSIX=1 -DPROJECTDIR=/home/lwss/Documents/cstrike15_src/vscript -DVPCGAME=csgo -DVPCGAMECAPS=CSGO  $(addprefix -I, $(abspath ../common ../public ../public/tier0 ../public/tier1 ../thirdparty/SDL2 ./languages/squirrel/include ./languages/squirrel/sqplus ./languages/lua/lua-5.1.4/src ./languages/squirrel/include ./languages/squirrel/sqplus ))) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/sqapi.o

$(OBJ_DIR)/sqbaselib.o: languages/squirrel/squirrel/sqbaselib.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/sqbaselib.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, -DVPC -DCSTRIKE_REL_BUILD=1 -DRAD_TELEMETRY_DISABLED -DNDEBUG -D_GLIBCXX_USE_CXX11_ABI=0 -DGNUC -DPOSIX -DCOMPILER_GCC -DMEMOVERRIDE_MODULE=vscript -D_DLL_EXT=_client.so -D_LINUX -DLINUX -DPOSIX -D_POSIX -DDLLNAME=vscript -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DUSE_SDL -DCSTRIKE15 -DVSCRIPT_DLL_EXPORT -DLUA_MOD_CASE_INSENSITIVE -DPROTECTED_THINGS_DISABLE -DVSCRIPT_DLL_EXPORT -D_DLL_EXT=_client.so -D_DLL_PREFIX=lib -D_EXTERNAL_DLL_EXT=.so -D_LINUX=1 -D_LINUXSTEAMRT64=1 -D_POSIX=1 -DLINUX=1 -DLINUX64=1 -DLINUXSTEAMRT64=1 -DPOSIX=1 -DPROJECTDIR=/home/lwss/Documents/cstrike15_src/vscript -DVPCGAME=csgo -DVPCGAMECAPS=CSGO  $(addprefix -I, $(abspath ../common ../public ../public/tier0 ../public/tier1 ../thirdparty/SDL2 ./languages/squirrel/include ./languages/squirrel/sqplus ./languages/lua/lua-5.1.4/src ./languages/squirrel/include ./languages/squirrel/sqplus ))) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/sqbaselib.o

$(OBJ_DIR)/sqclass.o: languages/squirrel/squirrel/sqclass.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/sqclass.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, -DVPC -DCSTRIKE_REL_BUILD=1 -DRAD_TELEMETRY_DISABLED -DNDEBUG -D_GLIBCXX_USE_CXX11_ABI=0 -DGNUC -DPOSIX -DCOMPILER_GCC -DMEMOVERRIDE_MODULE=vscript -D_DLL_EXT=_client.so -D_LINUX -DLINUX -DPOSIX -D_POSIX -DDLLNAME=vscript -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DUSE_SDL -DCSTRIKE15 -DVSCRIPT_DLL_EXPORT -DLUA_MOD_CASE_INSENSITIVE -DPROTECTED_THINGS_DISABLE -DVSCRIPT_DLL_EXPORT -D_DLL_EXT=_client.so -D_DLL_PREFIX=lib -D_EXTERNAL_DLL_EXT=.so -D_LINUX=1 -D_LINUXSTEAMRT64=1 -D_POSIX=1 -DLINUX=1 -DLINUX64=1 -DLINUXSTEAMRT64=1 -DPOSIX=1 -DPROJECTDIR=/home/lwss/Documents/cstrike15_src/vscript -DVPCGAME=csgo -DVPCGAMECAPS=CSGO  $(addprefix -I, $(abspath ../common ../public ../public/tier0 ../public/tier1 ../thirdparty/SDL2 ./languages/squirrel/include ./languages/squirrel/sqplus ./languages/lua/lua-5.1.4/src ./languages/squirrel/include ./languages/squirrel/sqplus ))) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/sqclass.o

$(OBJ_DIR)/sqcompiler.o: languages/squirrel/squirrel/sqcompiler.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/sqcompiler.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, -DVPC -DCSTRIKE_REL_BUILD=1 -DRAD_TELEMETRY_DISABLED -DNDEBUG -D_GLIBCXX_USE_CXX11_ABI=0 -DGNUC -DPOSIX -DCOMPILER_GCC -DMEMOVERRIDE_MODULE=vscript -D_DLL_EXT=_client.so -D_LINUX -DLINUX -DPOSIX -D_POSIX -DDLLNAME=vscript -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DUSE_SDL -DCSTRIKE15 -DVSCRIPT_DLL_EXPORT -DLUA_MOD_CASE_INSENSITIVE -DPROTECTED_THINGS_DISABLE -DVSCRIPT_DLL_EXPORT -D_DLL_EXT=_client.so -D_DLL_PREFIX=lib -D_EXTERNAL_DLL_EXT=.so -D_LINUX=1 -D_LINUXSTEAMRT64=1 -D_POSIX=1 -DLINUX=1 -DLINUX64=1 -DLINUXSTEAMRT64=1 -DPOSIX=1 -DPROJECTDIR=/home/lwss/Documents/cstrike15_src/vscript -DVPCGAME=csgo -DVPCGAMECAPS=CSGO  $(addprefix -I, $(abspath ../common ../public ../public/tier0 ../public/tier1 ../thirdparty/SDL2 ./languages/squirrel/include ./languages/squirrel/sqplus ./languages/lua/lua-5.1.4/src ./languages/squirrel/include ./languages/squirrel/sqplus ))) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/sqcompiler.o

$(OBJ_DIR)/sqdebug.o: languages/squirrel/squirrel/sqdebug.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/sqdebug.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, -DVPC -DCSTRIKE_REL_BUILD=1 -DRAD_TELEMETRY_DISABLED -DNDEBUG -D_GLIBCXX_USE_CXX11_ABI=0 -DGNUC -DPOSIX -DCOMPILER_GCC -DMEMOVERRIDE_MODULE=vscript -D_DLL_EXT=_client.so -D_LINUX -DLINUX -DPOSIX -D_POSIX -DDLLNAME=vscript -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DUSE_SDL -DCSTRIKE15 -DVSCRIPT_DLL_EXPORT -DLUA_MOD_CASE_INSENSITIVE -DPROTECTED_THINGS_DISABLE -DVSCRIPT_DLL_EXPORT -D_DLL_EXT=_client.so -D_DLL_PREFIX=lib -D_EXTERNAL_DLL_EXT=.so -D_LINUX=1 -D_LINUXSTEAMRT64=1 -D_POSIX=1 -DLINUX=1 -DLINUX64=1 -DLINUXSTEAMRT64=1 -DPOSIX=1 -DPROJECTDIR=/home/lwss/Documents/cstrike15_src/vscript -DVPCGAME=csgo -DVPCGAMECAPS=CSGO  $(addprefix -I, $(abspath ../common ../public ../public/tier0 ../public/tier1 ../thirdparty/SDL2 ./languages/squirrel/include ./languages/squirrel/sqplus ./languages/lua/lua-5.1.4/src ./languages/squirrel/include ./languages/squirrel/sqplus ))) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/sqdebug.o

$(OBJ_DIR)/sqfuncstate.o: languages/squirrel/squirrel/sqfuncstate.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/sqfuncstate.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, -DVPC -DCSTRIKE_REL_BUILD=1 -DRAD_TELEMETRY_DISABLED -DNDEBUG -D_GLIBCXX_USE_CXX11_ABI=0 -DGNUC -DPOSIX -DCOMPILER_GCC -DMEMOVERRIDE_MODULE=vscript -D_DLL_EXT=_client.so -D_LINUX -DLINUX -DPOSIX -D_POSIX -DDLLNAME=vscript -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DUSE_SDL -DCSTRIKE15 -DVSCRIPT_DLL_EXPORT -DLUA_MOD_CASE_INSENSITIVE -DPROTECTED_THINGS_DISABLE -DVSCRIPT_DLL_EXPORT -D_DLL_EXT=_client.so -D_DLL_PREFIX=lib -D_EXTERNAL_DLL_EXT=.so -D_LINUX=1 -D_LINUXSTEAMRT64=1 -D_POSIX=1 -DLINUX=1 -DLINUX64=1 -DLINUXSTEAMRT64=1 -DPOSIX=1 -DPROJECTDIR=/home/lwss/Documents/cstrike15_src/vscript -DVPCGAME=csgo -DVPCGAMECAPS=CSGO  $(addprefix -I, $(abspath ../common ../public ../public/tier0 ../public/tier1 ../thirdparty/SDL2 ./languages/squirrel/include ./languages/squirrel/sqplus ./languages/lua/lua-5.1.4/src ./languages/squirrel/include ./languages/squirrel/sqplus ))) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/sqfuncstate.o

$(OBJ_DIR)/sqlexer.o: languages/squirrel/squirrel/sqlexer.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/sqlexer.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, -DVPC -DCSTRIKE_REL_BUILD=1 -DRAD_TELEMETRY_DISABLED -DNDEBUG -D_GLIBCXX_USE_CXX11_ABI=0 -DGNUC -DPOSIX -DCOMPILER_GCC -DMEMOVERRIDE_MODULE=vscript -D_DLL_EXT=_client.so -D_LINUX -DLINUX -DPOSIX -D_POSIX -DDLLNAME=vscript -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DUSE_SDL -DCSTRIKE15 -DVSCRIPT_DLL_EXPORT -DLUA_MOD_CASE_INSENSITIVE -DPROTECTED_THINGS_DISABLE -DVSCRIPT_DLL_EXPORT -D_DLL_EXT=_client.so -D_DLL_PREFIX=lib -D_EXTERNAL_DLL_EXT=.so -D_LINUX=1 -D_LINUXSTEAMRT64=1 -D_POSIX=1 -DLINUX=1 -DLINUX64=1 -DLINUXSTEAMRT64=1 -DPOSIX=1 -DPROJECTDIR=/home/lwss/Documents/cstrike15_src/vscript -DVPCGAME=csgo -DVPCGAMECAPS=CSGO  $(addprefix -I, $(abspath ../common ../public ../public/tier0 ../public/tier1 ../thirdparty/SDL2 ./languages/squirrel/include ./languages/squirrel/sqplus ./languages/lua/lua-5.1.4/src ./languages/squirrel/include ./languages/squirrel/sqplus ))) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/sqlexer.o

$(OBJ_DIR)/sqmem.o: languages/squirrel/squirrel/sqmem.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/sqmem.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, -DVPC -DCSTRIKE_REL_BUILD=1 -DRAD_TELEMETRY_DISABLED -DNDEBUG -D_GLIBCXX_USE_CXX11_ABI=0 -DGNUC -DPOSIX -DCOMPILER_GCC -DMEMOVERRIDE_MODULE=vscript -D_DLL_EXT=_client.so -D_LINUX -DLINUX -DPOSIX -D_POSIX -DDLLNAME=vscript -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DUSE_SDL -DCSTRIKE15 -DVSCRIPT_DLL_EXPORT -DLUA_MOD_CASE_INSENSITIVE -DPROTECTED_THINGS_DISABLE -DVSCRIPT_DLL_EXPORT -D_DLL_EXT=_client.so -D_DLL_PREFIX=lib -D_EXTERNAL_DLL_EXT=.so -D_LINUX=1 -D_LINUXSTEAMRT64=1 -D_POSIX=1 -DLINUX=1 -DLINUX64=1 -DLINUXSTEAMRT64=1 -DPOSIX=1 -DPROJECTDIR=/home/lwss/Documents/cstrike15_src/vscript -DVPCGAME=csgo -DVPCGAMECAPS=CSGO  $(addprefix -I, $(abspath ../common ../public ../public/tier0 ../public/tier1 ../thirdparty/SDL2 ./languages/squirrel/include ./languages/squirrel/sqplus ./languages/lua/lua-5.1.4/src ./languages/squirrel/include ./languages/squirrel/sqplus ))) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/sqmem.o

$(OBJ_DIR)/sqobject.o: languages/squirrel/squirrel/sqobject.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/sqobject.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, -DVPC -DCSTRIKE_REL_BUILD=1 -DRAD_TELEMETRY_DISABLED -DNDEBUG -D_GLIBCXX_USE_CXX11_ABI=0 -DGNUC -DPOSIX -DCOMPILER_GCC -DMEMOVERRIDE_MODULE=vscript -D_DLL_EXT=_client.so -D_LINUX -DLINUX -DPOSIX -D_POSIX -DDLLNAME=vscript -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DUSE_SDL -DCSTRIKE15 -DVSCRIPT_DLL_EXPORT -DLUA_MOD_CASE_INSENSITIVE -DPROTECTED_THINGS_DISABLE -DVSCRIPT_DLL_EXPORT -D_DLL_EXT=_client.so -D_DLL_PREFIX=lib -D_EXTERNAL_DLL_EXT=.so -D_LINUX=1 -D_LINUXSTEAMRT64=1 -D_POSIX=1 -DLINUX=1 -DLINUX64=1 -DLINUXSTEAMRT64=1 -DPOSIX=1 -DPROJECTDIR=/home/lwss/Documents/cstrike15_src/vscript -DVPCGAME=csgo -DVPCGAMECAPS=CSGO  $(addprefix -I, $(abspath ../common ../public ../public/tier0 ../public/tier1 ../thirdparty/SDL2 ./languages/squirrel/include ./languages/squirrel/sqplus ./languages/lua/lua-5.1.4/src ./languages/squirrel/include ./languages/squirrel/sqplus ))) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/sqobject.o

$(OBJ_DIR)/sqstate.o: languages/squirrel/squirrel/sqstate.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/sqstate.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, -DVPC -DCSTRIKE_REL_BUILD=1 -DRAD_TELEMETRY_DISABLED -DNDEBUG -D_GLIBCXX_USE_CXX11_ABI=0 -DGNUC -DPOSIX -DCOMPILER_GCC -DMEMOVERRIDE_MODULE=vscript -D_DLL_EXT=_client.so -D_LINUX -DLINUX -DPOSIX -D_POSIX -DDLLNAME=vscript -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DUSE_SDL -DCSTRIKE15 -DVSCRIPT_DLL_EXPORT -DLUA_MOD_CASE_INSENSITIVE -DPROTECTED_THINGS_DISABLE -DVSCRIPT_DLL_EXPORT -D_DLL_EXT=_client.so -D_DLL_PREFIX=lib -D_EXTERNAL_DLL_EXT=.so -D_LINUX=1 -D_LINUXSTEAMRT64=1 -D_POSIX=1 -DLINUX=1 -DLINUX64=1 -DLINUXSTEAMRT64=1 -DPOSIX=1 -DPROJECTDIR=/home/lwss/Documents/cstrike15_src/vscript -DVPCGAME=csgo -DVPCGAMECAPS=CSGO  $(addprefix -I, $(abspath ../common ../public ../public/tier0 ../public/tier1 ../thirdparty/SDL2 ./languages/squirrel/include ./languages/squirrel/sqplus ./languages/lua/lua-5.1.4/src ./languages/squirrel/include ./languages/squirrel/sqplus ))) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/sqstate.o

$(OBJ_DIR)/sqtable.o: languages/squirrel/squirrel/sqtable.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/sqtable.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, -DVPC -DCSTRIKE_REL_BUILD=1 -DRAD_TELEMETRY_DISABLED -DNDEBUG -D_GLIBCXX_USE_CXX11_ABI=0 -DGNUC -DPOSIX -DCOMPILER_GCC -DMEMOVERRIDE_MODULE=vscript -D_DLL_EXT=_client.so -D_LINUX -DLINUX -DPOSIX -D_POSIX -DDLLNAME=vscript -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DUSE_SDL -DCSTRIKE15 -DVSCRIPT_DLL_EXPORT -DLUA_MOD_CASE_INSENSITIVE -DPROTECTED_THINGS_DISABLE -DVSCRIPT_DLL_EXPORT -D_DLL_EXT=_client.so -D_DLL_PREFIX=lib -D_EXTERNAL_DLL_EXT=.so -D_LINUX=1 -D_LINUXSTEAMRT64=1 -D_POSIX=1 -DLINUX=1 -DLINUX64=1 -DLINUXSTEAMRT64=1 -DPOSIX=1 -DPROJECTDIR=/home/lwss/Documents/cstrike15_src/vscript -DVPCGAME=csgo -DVPCGAMECAPS=CSGO  $(addprefix -I, $(abspath ../common ../public ../public/tier0 ../public/tier1 ../thirdparty/SDL2 ./languages/squirrel/include ./languages/squirrel/sqplus ./languages/lua/lua-5.1.4/src ./languages/squirrel/include ./languages/squirrel/sqplus ))) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/sqtable.o

$(OBJ_DIR)/sqvm.o: languages/squirrel/squirrel/sqvm.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/sqvm.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, -DVPC -DCSTRIKE_REL_BUILD=1 -DRAD_TELEMETRY_DISABLED -DNDEBUG -D_GLIBCXX_USE_CXX11_ABI=0 -DGNUC -DPOSIX -DCOMPILER_GCC -DMEMOVERRIDE_MODULE=vscript -D_DLL_EXT=_client.so -D_LINUX -DLINUX -DPOSIX -D_POSIX -DDLLNAME=vscript -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DUSE_SDL -DCSTRIKE15 -DVSCRIPT_DLL_EXPORT -DLUA_MOD_CASE_INSENSITIVE -DPROTECTED_THINGS_DISABLE -DVSCRIPT_DLL_EXPORT -D_DLL_EXT=_client.so -D_DLL_PREFIX=lib -D_EXTERNAL_DLL_EXT=.so -D_LINUX=1 -D_LINUXSTEAMRT64=1 -D_POSIX=1 -DLINUX=1 -DLINUX64=1 -DLINUXSTEAMRT64=1 -DPOSIX=1 -DPROJECTDIR=/home/lwss/Documents/cstrike15_src/vscript -DVPCGAME=csgo -DVPCGAMECAPS=CSGO  $(addprefix -I, $(abspath ../common ../public ../public/tier0 ../public/tier1 ../thirdparty/SDL2 ./languages/squirrel/include ./languages/squirrel/sqplus ./languages/lua/lua-5.1.4/src ./languages/squirrel/include ./languages/squirrel/sqplus ))) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/sqvm.o

$(OBJ_DIR)/sqrdbg.o: languages/squirrel/sqdbg/sqrdbg.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/sqrdbg.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, -DVPC -DCSTRIKE_REL_BUILD=1 -DRAD_TELEMETRY_DISABLED -DNDEBUG -D_GLIBCXX_USE_CXX11_ABI=0 -DGNUC -DPOSIX -DCOMPILER_GCC -DMEMOVERRIDE_MODULE=vscript -D_DLL_EXT=_client.so -D_LINUX -DLINUX -DPOSIX -D_POSIX -DDLLNAME=vscript -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DUSE_SDL -DCSTRIKE15 -DVSCRIPT_DLL_EXPORT -DLUA_MOD_CASE_INSENSITIVE -DPROTECTED_THINGS_DISABLE -DVSCRIPT_DLL_EXPORT -D_DLL_EXT=_client.so -D_DLL_PREFIX=lib -D_EXTERNAL_DLL_EXT=.so -D_LINUX=1 -D_LINUXSTEAMRT64=1 -D_POSIX=1 -DLINUX=1 -DLINUX64=1 -DLINUXSTEAMRT64=1 -DPOSIX=1 -DPROJECTDIR=/home/lwss/Documents/cstrike15_src/vscript -DVPCGAME=csgo -DVPCGAMECAPS=CSGO  $(addprefix -I, $(abspath ../common ../public ../public/tier0 ../public/tier1 ../thirdparty/SDL2 ./languages/squirrel/include ./languages/squirrel/sqplus ./languages/lua/lua-5.1.4/src ./languages/squirrel/include ./languages/squirrel/sqplus ))) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/sqrdbg.o

$(OBJ_DIR)/sqdbgserver.o: languages/squirrel/sqdbg/sqdbgserver.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/sqdbgserver.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, -DVPC -DCSTRIKE_REL_BUILD=1 -DRAD_TELEMETRY_DISABLED -DNDEBUG -D_GLIBCXX_USE_CXX11_ABI=0 -DGNUC -DPOSIX -DCOMPILER_GCC -DMEMOVERRIDE_MODULE=vscript -D_DLL_EXT=_client.so -D_LINUX -DLINUX -DPOSIX -D_POSIX -DDLLNAME=vscript -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DUSE_SDL -DCSTRIKE15 -DVSCRIPT_DLL_EXPORT -DLUA_MOD_CASE_INSENSITIVE -DPROTECTED_THINGS_DISABLE -DVSCRIPT_DLL_EXPORT -D_DLL_EXT=_client.so -D_DLL_PREFIX=lib -D_EXTERNAL_DLL_EXT=.so -D_LINUX=1 -D_LINUXSTEAMRT64=1 -D_POSIX=1 -DLINUX=1 -DLINUX64=1 -DLINUXSTEAMRT64=1 -DPOSIX=1 -DPROJECTDIR=/home/lwss/Documents/cstrike15_src/vscript -DVPCGAME=csgo -DVPCGAMECAPS=CSGO  $(addprefix -I, $(abspath ../common ../public ../public/tier0 ../public/tier1 ../thirdparty/SDL2 ./languages/squirrel/include ./languages/squirrel/sqplus ./languages/lua/lua-5.1.4/src ./languages/squirrel/include ./languages/squirrel/sqplus ))) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/sqdbgserver.o

$(OBJ_DIR)/sqstdaux.o: languages/squirrel/sqstdlib/sqstdaux.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/sqstdaux.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, -DVPC -DCSTRIKE_REL_BUILD=1 -DRAD_TELEMETRY_DISABLED -DNDEBUG -D_GLIBCXX_USE_CXX11_ABI=0 -DGNUC -DPOSIX -DCOMPILER_GCC -DMEMOVERRIDE_MODULE=vscript -D_DLL_EXT=_client.so -D_LINUX -DLINUX -DPOSIX -D_POSIX -DDLLNAME=vscript -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DUSE_SDL -DCSTRIKE15 -DVSCRIPT_DLL_EXPORT -DLUA_MOD_CASE_INSENSITIVE -DPROTECTED_THINGS_DISABLE -DVSCRIPT_DLL_EXPORT -D_DLL_EXT=_client.so -D_DLL_PREFIX=lib -D_EXTERNAL_DLL_EXT=.so -D_LINUX=1 -D_LINUXSTEAMRT64=1 -D_POSIX=1 -DLINUX=1 -DLINUX64=1 -DLINUXSTEAMRT64=1 -DPOSIX=1 -DPROJECTDIR=/home/lwss/Documents/cstrike15_src/vscript -DVPCGAME=csgo -DVPCGAMECAPS=CSGO  $(addprefix -I, $(abspath ../common ../public ../public/tier0 ../public/tier1 ../thirdparty/SDL2 ./languages/squirrel/include ./languages/squirrel/sqplus ./languages/lua/lua-5.1.4/src ./languages/squirrel/include ./languages/squirrel/sqplus ))) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/sqstdaux.o

$(OBJ_DIR)/sqstdblob.o: languages/squirrel/sqstdlib/sqstdblob.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/sqstdblob.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, -DVPC -DCSTRIKE_REL_BUILD=1 -DRAD_TELEMETRY_DISABLED -DNDEBUG -D_GLIBCXX_USE_CXX11_ABI=0 -DGNUC -DPOSIX -DCOMPILER_GCC -DMEMOVERRIDE_MODULE=vscript -D_DLL_EXT=_client.so -D_LINUX -DLINUX -DPOSIX -D_POSIX -DDLLNAME=vscript -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DUSE_SDL -DCSTRIKE15 -DVSCRIPT_DLL_EXPORT -DLUA_MOD_CASE_INSENSITIVE -DPROTECTED_THINGS_DISABLE -DVSCRIPT_DLL_EXPORT -D_DLL_EXT=_client.so -D_DLL_PREFIX=lib -D_EXTERNAL_DLL_EXT=.so -D_LINUX=1 -D_LINUXSTEAMRT64=1 -D_POSIX=1 -DLINUX=1 -DLINUX64=1 -DLINUXSTEAMRT64=1 -DPOSIX=1 -DPROJECTDIR=/home/lwss/Documents/cstrike15_src/vscript -DVPCGAME=csgo -DVPCGAMECAPS=CSGO  $(addprefix -I, $(abspath ../common ../public ../public/tier0 ../public/tier1 ../thirdparty/SDL2 ./languages/squirrel/include ./languages/squirrel/sqplus ./languages/lua/lua-5.1.4/src ./languages/squirrel/include ./languages/squirrel/sqplus ))) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/sqstdblob.o

$(OBJ_DIR)/sqstdmath.o: languages/squirrel/sqstdlib/sqstdmath.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/sqstdmath.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, -DVPC -DCSTRIKE_REL_BUILD=1 -DRAD_TELEMETRY_DISABLED -DNDEBUG -D_GLIBCXX_USE_CXX11_ABI=0 -DGNUC -DPOSIX -DCOMPILER_GCC -DMEMOVERRIDE_MODULE=vscript -D_DLL_EXT=_client.so -D_LINUX -DLINUX -DPOSIX -D_POSIX -DDLLNAME=vscript -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DUSE_SDL -DCSTRIKE15 -DVSCRIPT_DLL_EXPORT -DLUA_MOD_CASE_INSENSITIVE -DPROTECTED_THINGS_DISABLE -DVSCRIPT_DLL_EXPORT -D_DLL_EXT=_client.so -D_DLL_PREFIX=lib -D_EXTERNAL_DLL_EXT=.so -D_LINUX=1 -D_LINUXSTEAMRT64=1 -D_POSIX=1 -DLINUX=1 -DLINUX64=1 -DLINUXSTEAMRT64=1 -DPOSIX=1 -DPROJECTDIR=/home/lwss/Documents/cstrike15_src/vscript -DVPCGAME=csgo -DVPCGAMECAPS=CSGO  $(addprefix -I, $(abspath ../common ../public ../public/tier0 ../public/tier1 ../thirdparty/SDL2 ./languages/squirrel/include ./languages/squirrel/sqplus ./languages/lua/lua-5.1.4/src ./languages/squirrel/include ./languages/squirrel/sqplus ))) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/sqstdmath.o

$(OBJ_DIR)/sqstdrex.o: languages/squirrel/sqstdlib/sqstdrex.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/sqstdrex.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, -DVPC -DCSTRIKE_REL_BUILD=1 -DRAD_TELEMETRY_DISABLED -DNDEBUG -D_GLIBCXX_USE_CXX11_ABI=0 -DGNUC -DPOSIX -DCOMPILER_GCC -DMEMOVERRIDE_MODULE=vscript -D_DLL_EXT=_client.so -D_LINUX -DLINUX -DPOSIX -D_POSIX -DDLLNAME=vscript -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DUSE_SDL -DCSTRIKE15 -DVSCRIPT_DLL_EXPORT -DLUA_MOD_CASE_INSENSITIVE -DPROTECTED_THINGS_DISABLE -DVSCRIPT_DLL_EXPORT -D_DLL_EXT=_client.so -D_DLL_PREFIX=lib -D_EXTERNAL_DLL_EXT=.so -D_LINUX=1 -D_LINUXSTEAMRT64=1 -D_POSIX=1 -DLINUX=1 -DLINUX64=1 -DLINUXSTEAMRT64=1 -DPOSIX=1 -DPROJECTDIR=/home/lwss/Documents/cstrike15_src/vscript -DVPCGAME=csgo -DVPCGAMECAPS=CSGO  $(addprefix -I, $(abspath ../common ../public ../public/tier0 ../public/tier1 ../thirdparty/SDL2 ./languages/squirrel/include ./languages/squirrel/sqplus ./languages/lua/lua-5.1.4/src ./languages/squirrel/include ./languages/squirrel/sqplus ))) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/sqstdrex.o

$(OBJ_DIR)/sqstdstream.o: languages/squirrel/sqstdlib/sqstdstream.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/sqstdstream.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, -DVPC -DCSTRIKE_REL_BUILD=1 -DRAD_TELEMETRY_DISABLED -DNDEBUG -D_GLIBCXX_USE_CXX11_ABI=0 -DGNUC -DPOSIX -DCOMPILER_GCC -DMEMOVERRIDE_MODULE=vscript -D_DLL_EXT=_client.so -D_LINUX -DLINUX -DPOSIX -D_POSIX -DDLLNAME=vscript -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DUSE_SDL -DCSTRIKE15 -DVSCRIPT_DLL_EXPORT -DLUA_MOD_CASE_INSENSITIVE -DPROTECTED_THINGS_DISABLE -DVSCRIPT_DLL_EXPORT -D_DLL_EXT=_client.so -D_DLL_PREFIX=lib -D_EXTERNAL_DLL_EXT=.so -D_LINUX=1 -D_LINUXSTEAMRT64=1 -D_POSIX=1 -DLINUX=1 -DLINUX64=1 -DLINUXSTEAMRT64=1 -DPOSIX=1 -DPROJECTDIR=/home/lwss/Documents/cstrike15_src/vscript -DVPCGAME=csgo -DVPCGAMECAPS=CSGO  $(addprefix -I, $(abspath ../common ../public ../public/tier0 ../public/tier1 ../thirdparty/SDL2 ./languages/squirrel/include ./languages/squirrel/sqplus ./languages/lua/lua-5.1.4/src ./languages/squirrel/include ./languages/squirrel/sqplus ))) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/sqstdstream.o

$(OBJ_DIR)/sqstdstring.o: languages/squirrel/sqstdlib/sqstdstring.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/sqstdstring.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, -DVPC -DCSTRIKE_REL_BUILD=1 -DRAD_TELEMETRY_DISABLED -DNDEBUG -D_GLIBCXX_USE_CXX11_ABI=0 -DGNUC -DPOSIX -DCOMPILER_GCC -DMEMOVERRIDE_MODULE=vscript -D_DLL_EXT=_client.so -D_LINUX -DLINUX -DPOSIX -D_POSIX -DDLLNAME=vscript -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DUSE_SDL -DCSTRIKE15 -DVSCRIPT_DLL_EXPORT -DLUA_MOD_CASE_INSENSITIVE -DPROTECTED_THINGS_DISABLE -DVSCRIPT_DLL_EXPORT -D_DLL_EXT=_client.so -D_DLL_PREFIX=lib -D_EXTERNAL_DLL_EXT=.so -D_LINUX=1 -D_LINUXSTEAMRT64=1 -D_POSIX=1 -DLINUX=1 -DLINUX64=1 -DLINUXSTEAMRT64=1 -DPOSIX=1 -DPROJECTDIR=/home/lwss/Documents/cstrike15_src/vscript -DVPCGAME=csgo -DVPCGAMECAPS=CSGO  $(addprefix -I, $(abspath ../common ../public ../public/tier0 ../public/tier1 ../thirdparty/SDL2 ./languages/squirrel/include ./languages/squirrel/sqplus ./languages/lua/lua-5.1.4/src ./languages/squirrel/include ./languages/squirrel/sqplus ))) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/sqstdstring.o

$(OBJ_DIR)/SqPlus.o: languages/squirrel/sqplus/SqPlus.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/SqPlus.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, -DVPC -DCSTRIKE_REL_BUILD=1 -DRAD_TELEMETRY_DISABLED -DNDEBUG -D_GLIBCXX_USE_CXX11_ABI=0 -DGNUC -DPOSIX -DCOMPILER_GCC -DMEMOVERRIDE_MODULE=vscript -D_DLL_EXT=_client.so -D_LINUX -DLINUX -DPOSIX -D_POSIX -DDLLNAME=vscript -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DUSE_SDL -DCSTRIKE15 -DVSCRIPT_DLL_EXPORT -DLUA_MOD_CASE_INSENSITIVE -DPROTECTED_THINGS_DISABLE -DVSCRIPT_DLL_EXPORT -D_DLL_EXT=_client.so -D_DLL_PREFIX=lib -D_EXTERNAL_DLL_EXT=.so -D_LINUX=1 -D_LINUXSTEAMRT64=1 -D_POSIX=1 -DLINUX=1 -DLINUX64=1 -DLINUXSTEAMRT64=1 -DPOSIX=1 -DPROJECTDIR=/home/lwss/Documents/cstrike15_src/vscript -DVPCGAME=csgo -DVPCGAMECAPS=CSGO  $(addprefix -I, $(abspath ../common ../public ../public/tier0 ../public/tier1 ../thirdparty/SDL2 ./languages/squirrel/include ./languages/squirrel/sqplus ./languages/lua/lua-5.1.4/src ./languages/squirrel/include ./languages/squirrel/sqplus ))) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/SqPlus.o

$(OBJ_DIR)/SquirrelBindingsUtils.o: languages/squirrel/sqplus/SquirrelBindingsUtils.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/SquirrelBindingsUtils.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, -DVPC -DCSTRIKE_REL_BUILD=1 -DRAD_TELEMETRY_DISABLED -DNDEBUG -D_GLIBCXX_USE_CXX11_ABI=0 -DGNUC -DPOSIX -DCOMPILER_GCC -DMEMOVERRIDE_MODULE=vscript -D_DLL_EXT=_client.so -D_LINUX -DLINUX -DPOSIX -D_POSIX -DDLLNAME=vscript -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DUSE_SDL -DCSTRIKE15 -DVSCRIPT_DLL_EXPORT -DLUA_MOD_CASE_INSENSITIVE -DPROTECTED_THINGS_DISABLE -DVSCRIPT_DLL_EXPORT -D_DLL_EXT=_client.so -D_DLL_PREFIX=lib -D_EXTERNAL_DLL_EXT=.so -D_LINUX=1 -D_LINUXSTEAMRT64=1 -D_POSIX=1 -DLINUX=1 -DLINUX64=1 -DLINUXSTEAMRT64=1 -DPOSIX=1 -DPROJECTDIR=/home/lwss/Documents/cstrike15_src/vscript -DVPCGAME=csgo -DVPCGAMECAPS=CSGO  $(addprefix -I, $(abspath ../common ../public ../public/tier0 ../public/tier1 ../thirdparty/SDL2 ./languages/squirrel/include ./languages/squirrel/sqplus ./languages/lua/lua-5.1.4/src ./languages/squirrel/include ./languages/squirrel/sqplus ))) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/SquirrelBindingsUtils.o

$(OBJ_DIR)/SquirrelObject.o: languages/squirrel/sqplus/SquirrelObject.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/SquirrelObject.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, -DVPC -DCSTRIKE_REL_BUILD=1 -DRAD_TELEMETRY_DISABLED -DNDEBUG -D_GLIBCXX_USE_CXX11_ABI=0 -DGNUC -DPOSIX -DCOMPILER_GCC -DMEMOVERRIDE_MODULE=vscript -D_DLL_EXT=_client.so -D_LINUX -DLINUX -DPOSIX -D_POSIX -DDLLNAME=vscript -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DUSE_SDL -DCSTRIKE15 -DVSCRIPT_DLL_EXPORT -DLUA_MOD_CASE_INSENSITIVE -DPROTECTED_THINGS_DISABLE -DVSCRIPT_DLL_EXPORT -D_DLL_EXT=_client.so -D_DLL_PREFIX=lib -D_EXTERNAL_DLL_EXT=.so -D_LINUX=1 -D_LINUXSTEAMRT64=1 -D_POSIX=1 -DLINUX=1 -DLINUX64=1 -DLINUXSTEAMRT64=1 -DPOSIX=1 -DPROJECTDIR=/home/lwss/Documents/cstrike15_src/vscript -DVPCGAME=csgo -DVPCGAMECAPS=CSGO  $(addprefix -I, $(abspath ../common ../public ../public/tier0 ../public/tier1 ../thirdparty/SDL2 ./languages/squirrel/include ./languages/squirrel/sqplus ./languages/lua/lua-5.1.4/src ./languages/squirrel/include ./languages/squirrel/sqplus ))) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/SquirrelObject.o

$(OBJ_DIR)/SquirrelVM.o: languages/squirrel/sqplus/SquirrelVM.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/SquirrelVM.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, -DVPC -DCSTRIKE_REL_BUILD=1 -DRAD_TELEMETRY_DISABLED -DNDEBUG -D_GLIBCXX_USE_CXX11_ABI=0 -DGNUC -DPOSIX -DCOMPILER_GCC -DMEMOVERRIDE_MODULE=vscript -D_DLL_EXT=_client.so -D_LINUX -DLINUX -DPOSIX -D_POSIX -DDLLNAME=vscript -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DUSE_SDL -DCSTRIKE15 -DVSCRIPT_DLL_EXPORT -DLUA_MOD_CASE_INSENSITIVE -DPROTECTED_THINGS_DISABLE -DVSCRIPT_DLL_EXPORT -D_DLL_EXT=_client.so -D_DLL_PREFIX=lib -D_EXTERNAL_DLL_EXT=.so -D_LINUX=1 -D_LINUXSTEAMRT64=1 -D_POSIX=1 -DLINUX=1 -DLINUX64=1 -DLINUXSTEAMRT64=1 -DPOSIX=1 -DPROJECTDIR=/home/lwss/Documents/cstrike15_src/vscript -DVPCGAME=csgo -DVPCGAMECAPS=CSGO  $(addprefix -I, $(abspath ../common ../public ../public/tier0 ../public/tier1 ../thirdparty/SDL2 ./languages/squirrel/include ./languages/squirrel/sqplus ./languages/lua/lua-5.1.4/src ./languages/squirrel/include ./languages/squirrel/sqplus ))) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/SquirrelVM.o

endif # (CFG=release)
