#ifndef HK_PHYSICS_BLUEPRINT_TYPES_H
#define HK_PHYSICS_BLUEPRINT_TYPES_H


//: Autogenerated file.
//  Clients may append new types
//  

enum hk_Blueprint_Types
{
	HK_UNDEFINED		= 0,
	HK_GEOMETRY_TYPE	= 1,

	HK_CONSTRAINT_TYPE  = 100,

	HK_VEHICLE_TYPE				= 200,	// @@@ OS Naming Conventions to be discussed
	HK_VEHICLE_BASE_TYPE			= 201,	// @@@ OS Naming Conventions to be discussed
	HK_VEHICLE_BRAKES_TYPE			= 202,	// @@@ OS Naming Conventions to be discussed
	HK_VEHICLE_BRAKES_DEFAULT_TYPE		= 203,	// @@@ OS Naming Conventions to be discussed
	HK_VEHICLE_CAMERA_TYPE			= 204,	// @@@ OS Naming Conventions to be discussed
	HK_VEHICLE_CAMERA_DEFAULT_TYPE		= 204,	// @@@ OS Naming Conventions to be discussed
	HK_VEHICLE_ENGINE_TYPE			= 205,	// @@@ OS Naming Conventions to be discussed
	HK_VEHICLE_ENGINE_DEFAULT_TYPE		= 206,	// @@@ OS Naming Conventions to be discussed
	HK_VEHICLE_EXTRAS_TYPE			= 207,	// @@@ OS Naming Conventions to be discussed
	HK_VEHICLE_INPUT_TYPE			= 208,	// @@@ OS Naming Conventions to be discussed
	HK_VEHICLE_INPUT_DEFAULT_TYPE		= 209,	// @@@ OS Naming Conventions to be discussed
	HK_VEHICLE_SOUNDINTERFACE_TYPE		= 210,	// @@@ OS Naming Conventions to be discussed
	HK_VEHICLE_SOUNDINTERFACE_DEFAULT_TYPE	= 210,	// @@@ OS Naming Conventions to be discussed
	HK_VEHICLE_STEERING_TYPE		= 211,	// @@@ OS Naming Conventions to be discussed
	HK_VEHICLE_STEERING_DEFAULT_TYPE	= 212,	// @@@ OS Naming Conventions to be discussed
	HK_VEHICLE_SUSPENSION_TYPE		= 213,	// @@@ OS Naming Conventions to be discussed
	HK_VEHICLE_SUSPENSION_DEFAULT_TYPE	= 214,	// @@@ OS Naming Conventions to be discussed
	HK_VEHICLE_TRANSMISSION_TYPE		= 215,	// @@@ OS Naming Conventions to be discussed
	HK_VEHICLE_TRANSMISSION_AUTOMATIC_TYPE	= 216,	// @@@ OS Naming Conventions to be discussed
	HK_VEHICLE_WHEELS_TYPE			= 217	// @@@ OS Naming Conventions to be discussed
	

	// USER GENERATED START AT 65537
};

#endif /*HK_PHYSICS_BLUEPRINT_TYPES_H*/

